/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  fragment FullEntity on Entity {\n    id\n    name\n    description\n    spaceIds\n\n    types {\n      id\n      name\n    }\n\n    valuesList {\n      spaceId\n      property {\n        ...PropertyFragment\n      }\n      value\n      language\n      unit\n    }\n\n    relationsList {\n      id\n      spaceId\n      position\n      verified\n      entityId\n      fromEntity {\n        id\n        name\n      }\n      toEntity {\n        id\n        name\n        types {\n          id\n          name\n        }\n        valuesList {\n          propertyId\n          value\n        }\n      }\n      toSpaceId\n      type {\n        id\n        name\n        renderableType\n      }\n    }\n  }\n": typeof types.FullEntityFragmentDoc,
    "\n  query AllEntities($spaceId: UUID, $limit: Int, $offset: Int) {\n    entities(first: $limit, offset: $offset) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n": typeof types.AllEntitiesDocument,
    "\n  query EntitiesBatch($filter: EntityFilter, $spaceId: UUID) {\n    entities(filter: $filter) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n": typeof types.EntitiesBatchDocument,
    "\n  query Entity($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n": typeof types.EntityDocument,
    "\n  fragment FullRelation on Relation {\n    id\n    spaceId\n    position\n    verified\n    entityId\n    entity {\n      id\n      name\n    }\n    toEntity {\n      id\n      name\n      types {\n        id\n        name\n      }\n      valuesList {\n        propertyId\n        value\n      }\n    }\n    toSpaceId\n    type {\n      id\n      name\n      renderableType\n    }\n  }\n": typeof types.FullRelationFragmentDoc,
    "\n  query RelationEntityRelations($id: UUID!, $spaceId: UUID) {\n    relations(filter: { entityId: { is: $id }, spaceId: { is: $spaceId } }) {\n      ...FullRelation\n    }\n  }\n": typeof types.RelationEntityRelationsDocument,
    "\n  query EntityPage($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n    relations(filter: { entityId: { is: $id }, spaceId: { is: $spaceId } }) {\n      ...FullRelation\n    }\n  }\n": typeof types.EntityPageDocument,
    "\n  query EntityTypes($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      types(filter: { spaceIds: { in: [$spaceId] } }) {\n        id\n        name\n      }\n    }\n  }\n": typeof types.EntityTypesDocument,
    "\n  query EntityBacklinksPage($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      backlinksList(filter: { spaceId: { is: $spaceId } }) {\n        fromEntity {\n          id\n          name\n          spaceIds\n        }\n      }\n    }\n  }\n": typeof types.EntityBacklinksPageDocument,
    "\n  fragment FullSpace on Space {\n    id\n    type\n    daoAddress\n    spaceAddress\n    mainVotingAddress\n    membershipAddress\n    personalAddress\n\n    membersList {\n      address\n    }\n\n    editorsList {\n      address\n    }\n\n    page {\n      ...FullEntity\n    }\n  }\n": typeof types.FullSpaceFragmentDoc,
    "\n  query Space($id: UUID!) {\n    space(id: $id) {\n      ...FullSpace\n    }\n  }\n": typeof types.SpaceDocument,
    "\n  query Spaces($filter: SpaceFilter, $limit: Int, $offset: Int) {\n    spaces(filter: $filter, first: $limit, offset: $offset) {\n      ...FullSpace\n    }\n  }\n": typeof types.SpacesDocument,
    "\n  fragment PropertyFragment on Property {\n    id\n    name\n    dataType\n    renderableType\n    relationValueTypes {\n      id\n      name\n    }\n  }\n": typeof types.PropertyFragmentFragmentDoc,
    "\n  query Property($id: UUID!) {\n    property(id: $id) {\n      ...PropertyFragment\n    }\n  }\n": typeof types.PropertyDocument,
    "\n  query PropertiesBatch($ids: [UUID!]!) {\n    properties(filter: { id: { in: $ids } }) {\n      ...PropertyFragment\n    }\n  }\n": typeof types.PropertiesBatchDocument,
    "\n  query Result($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n      types {\n        id\n        name\n      }\n    }\n  }\n": typeof types.ResultDocument,
    "\n  query Results($query: String!, $filter: EntityFilter, $spaceId: UUID, $limit: Int, $offset: Int) {\n    search(query: $query, filter: $filter, spaceId: $spaceId, first: $limit, offset: $offset) {\n      id\n      name\n      description\n      spaceIds\n      types {\n        id\n        name\n      }\n    }\n  }\n": typeof types.ResultsDocument,
};
const documents: Documents = {
    "\n  fragment FullEntity on Entity {\n    id\n    name\n    description\n    spaceIds\n\n    types {\n      id\n      name\n    }\n\n    valuesList {\n      spaceId\n      property {\n        ...PropertyFragment\n      }\n      value\n      language\n      unit\n    }\n\n    relationsList {\n      id\n      spaceId\n      position\n      verified\n      entityId\n      fromEntity {\n        id\n        name\n      }\n      toEntity {\n        id\n        name\n        types {\n          id\n          name\n        }\n        valuesList {\n          propertyId\n          value\n        }\n      }\n      toSpaceId\n      type {\n        id\n        name\n        renderableType\n      }\n    }\n  }\n": types.FullEntityFragmentDoc,
    "\n  query AllEntities($spaceId: UUID, $limit: Int, $offset: Int) {\n    entities(first: $limit, offset: $offset) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n": types.AllEntitiesDocument,
    "\n  query EntitiesBatch($filter: EntityFilter, $spaceId: UUID) {\n    entities(filter: $filter) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n": types.EntitiesBatchDocument,
    "\n  query Entity($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n": types.EntityDocument,
    "\n  fragment FullRelation on Relation {\n    id\n    spaceId\n    position\n    verified\n    entityId\n    entity {\n      id\n      name\n    }\n    toEntity {\n      id\n      name\n      types {\n        id\n        name\n      }\n      valuesList {\n        propertyId\n        value\n      }\n    }\n    toSpaceId\n    type {\n      id\n      name\n      renderableType\n    }\n  }\n": types.FullRelationFragmentDoc,
    "\n  query RelationEntityRelations($id: UUID!, $spaceId: UUID) {\n    relations(filter: { entityId: { is: $id }, spaceId: { is: $spaceId } }) {\n      ...FullRelation\n    }\n  }\n": types.RelationEntityRelationsDocument,
    "\n  query EntityPage($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n    relations(filter: { entityId: { is: $id }, spaceId: { is: $spaceId } }) {\n      ...FullRelation\n    }\n  }\n": types.EntityPageDocument,
    "\n  query EntityTypes($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      types(filter: { spaceIds: { in: [$spaceId] } }) {\n        id\n        name\n      }\n    }\n  }\n": types.EntityTypesDocument,
    "\n  query EntityBacklinksPage($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      backlinksList(filter: { spaceId: { is: $spaceId } }) {\n        fromEntity {\n          id\n          name\n          spaceIds\n        }\n      }\n    }\n  }\n": types.EntityBacklinksPageDocument,
    "\n  fragment FullSpace on Space {\n    id\n    type\n    daoAddress\n    spaceAddress\n    mainVotingAddress\n    membershipAddress\n    personalAddress\n\n    membersList {\n      address\n    }\n\n    editorsList {\n      address\n    }\n\n    page {\n      ...FullEntity\n    }\n  }\n": types.FullSpaceFragmentDoc,
    "\n  query Space($id: UUID!) {\n    space(id: $id) {\n      ...FullSpace\n    }\n  }\n": types.SpaceDocument,
    "\n  query Spaces($filter: SpaceFilter, $limit: Int, $offset: Int) {\n    spaces(filter: $filter, first: $limit, offset: $offset) {\n      ...FullSpace\n    }\n  }\n": types.SpacesDocument,
    "\n  fragment PropertyFragment on Property {\n    id\n    name\n    dataType\n    renderableType\n    relationValueTypes {\n      id\n      name\n    }\n  }\n": types.PropertyFragmentFragmentDoc,
    "\n  query Property($id: UUID!) {\n    property(id: $id) {\n      ...PropertyFragment\n    }\n  }\n": types.PropertyDocument,
    "\n  query PropertiesBatch($ids: [UUID!]!) {\n    properties(filter: { id: { in: $ids } }) {\n      ...PropertyFragment\n    }\n  }\n": types.PropertiesBatchDocument,
    "\n  query Result($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n      types {\n        id\n        name\n      }\n    }\n  }\n": types.ResultDocument,
    "\n  query Results($query: String!, $filter: EntityFilter, $spaceId: UUID, $limit: Int, $offset: Int) {\n    search(query: $query, filter: $filter, spaceId: $spaceId, first: $limit, offset: $offset) {\n      id\n      name\n      description\n      spaceIds\n      types {\n        id\n        name\n      }\n    }\n  }\n": types.ResultsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment FullEntity on Entity {\n    id\n    name\n    description\n    spaceIds\n\n    types {\n      id\n      name\n    }\n\n    valuesList {\n      spaceId\n      property {\n        ...PropertyFragment\n      }\n      value\n      language\n      unit\n    }\n\n    relationsList {\n      id\n      spaceId\n      position\n      verified\n      entityId\n      fromEntity {\n        id\n        name\n      }\n      toEntity {\n        id\n        name\n        types {\n          id\n          name\n        }\n        valuesList {\n          propertyId\n          value\n        }\n      }\n      toSpaceId\n      type {\n        id\n        name\n        renderableType\n      }\n    }\n  }\n"): (typeof documents)["\n  fragment FullEntity on Entity {\n    id\n    name\n    description\n    spaceIds\n\n    types {\n      id\n      name\n    }\n\n    valuesList {\n      spaceId\n      property {\n        ...PropertyFragment\n      }\n      value\n      language\n      unit\n    }\n\n    relationsList {\n      id\n      spaceId\n      position\n      verified\n      entityId\n      fromEntity {\n        id\n        name\n      }\n      toEntity {\n        id\n        name\n        types {\n          id\n          name\n        }\n        valuesList {\n          propertyId\n          value\n        }\n      }\n      toSpaceId\n      type {\n        id\n        name\n        renderableType\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AllEntities($spaceId: UUID, $limit: Int, $offset: Int) {\n    entities(first: $limit, offset: $offset) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query AllEntities($spaceId: UUID, $limit: Int, $offset: Int) {\n    entities(first: $limit, offset: $offset) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query EntitiesBatch($filter: EntityFilter, $spaceId: UUID) {\n    entities(filter: $filter) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query EntitiesBatch($filter: EntityFilter, $spaceId: UUID) {\n    entities(filter: $filter) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Entity($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query Entity($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment FullRelation on Relation {\n    id\n    spaceId\n    position\n    verified\n    entityId\n    entity {\n      id\n      name\n    }\n    toEntity {\n      id\n      name\n      types {\n        id\n        name\n      }\n      valuesList {\n        propertyId\n        value\n      }\n    }\n    toSpaceId\n    type {\n      id\n      name\n      renderableType\n    }\n  }\n"): (typeof documents)["\n  fragment FullRelation on Relation {\n    id\n    spaceId\n    position\n    verified\n    entityId\n    entity {\n      id\n      name\n    }\n    toEntity {\n      id\n      name\n      types {\n        id\n        name\n      }\n      valuesList {\n        propertyId\n        value\n      }\n    }\n    toSpaceId\n    type {\n      id\n      name\n      renderableType\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query RelationEntityRelations($id: UUID!, $spaceId: UUID) {\n    relations(filter: { entityId: { is: $id }, spaceId: { is: $spaceId } }) {\n      ...FullRelation\n    }\n  }\n"): (typeof documents)["\n  query RelationEntityRelations($id: UUID!, $spaceId: UUID) {\n    relations(filter: { entityId: { is: $id }, spaceId: { is: $spaceId } }) {\n      ...FullRelation\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query EntityPage($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n    relations(filter: { entityId: { is: $id }, spaceId: { is: $spaceId } }) {\n      ...FullRelation\n    }\n  }\n"): (typeof documents)["\n  query EntityPage($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n\n      types {\n        id\n        name\n      }\n\n      valuesList(filter: { spaceId: { is: $spaceId } }) {\n        spaceId\n        property {\n          ...PropertyFragment\n        }\n        value\n        language\n        unit\n      }\n\n      relationsList(filter: { spaceId: { is: $spaceId } }) {\n        id\n        spaceId\n        position\n        verified\n        entityId\n        fromEntity {\n          id\n          name\n        }\n        toEntity {\n          id\n          name\n          types {\n            id\n            name\n          }\n          valuesList {\n            propertyId\n            value\n          }\n        }\n        toSpaceId\n        type {\n          id\n          name\n          renderableType\n        }\n      }\n    }\n    relations(filter: { entityId: { is: $id }, spaceId: { is: $spaceId } }) {\n      ...FullRelation\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query EntityTypes($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      types(filter: { spaceIds: { in: [$spaceId] } }) {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query EntityTypes($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      types(filter: { spaceIds: { in: [$spaceId] } }) {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query EntityBacklinksPage($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      backlinksList(filter: { spaceId: { is: $spaceId } }) {\n        fromEntity {\n          id\n          name\n          spaceIds\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query EntityBacklinksPage($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      backlinksList(filter: { spaceId: { is: $spaceId } }) {\n        fromEntity {\n          id\n          name\n          spaceIds\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment FullSpace on Space {\n    id\n    type\n    daoAddress\n    spaceAddress\n    mainVotingAddress\n    membershipAddress\n    personalAddress\n\n    membersList {\n      address\n    }\n\n    editorsList {\n      address\n    }\n\n    page {\n      ...FullEntity\n    }\n  }\n"): (typeof documents)["\n  fragment FullSpace on Space {\n    id\n    type\n    daoAddress\n    spaceAddress\n    mainVotingAddress\n    membershipAddress\n    personalAddress\n\n    membersList {\n      address\n    }\n\n    editorsList {\n      address\n    }\n\n    page {\n      ...FullEntity\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Space($id: UUID!) {\n    space(id: $id) {\n      ...FullSpace\n    }\n  }\n"): (typeof documents)["\n  query Space($id: UUID!) {\n    space(id: $id) {\n      ...FullSpace\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Spaces($filter: SpaceFilter, $limit: Int, $offset: Int) {\n    spaces(filter: $filter, first: $limit, offset: $offset) {\n      ...FullSpace\n    }\n  }\n"): (typeof documents)["\n  query Spaces($filter: SpaceFilter, $limit: Int, $offset: Int) {\n    spaces(filter: $filter, first: $limit, offset: $offset) {\n      ...FullSpace\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment PropertyFragment on Property {\n    id\n    name\n    dataType\n    renderableType\n    relationValueTypes {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  fragment PropertyFragment on Property {\n    id\n    name\n    dataType\n    renderableType\n    relationValueTypes {\n      id\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Property($id: UUID!) {\n    property(id: $id) {\n      ...PropertyFragment\n    }\n  }\n"): (typeof documents)["\n  query Property($id: UUID!) {\n    property(id: $id) {\n      ...PropertyFragment\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query PropertiesBatch($ids: [UUID!]!) {\n    properties(filter: { id: { in: $ids } }) {\n      ...PropertyFragment\n    }\n  }\n"): (typeof documents)["\n  query PropertiesBatch($ids: [UUID!]!) {\n    properties(filter: { id: { in: $ids } }) {\n      ...PropertyFragment\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Result($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n      types {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query Result($id: UUID!, $spaceId: UUID) {\n    entity(id: $id) {\n      id\n      name\n      description\n      spaceIds\n      types {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Results($query: String!, $filter: EntityFilter, $spaceId: UUID, $limit: Int, $offset: Int) {\n    search(query: $query, filter: $filter, spaceId: $spaceId, first: $limit, offset: $offset) {\n      id\n      name\n      description\n      spaceIds\n      types {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query Results($query: String!, $filter: EntityFilter, $spaceId: UUID, $limit: Int, $offset: Int) {\n    search(query: $query, filter: $filter, spaceId: $spaceId, first: $limit, offset: $offset) {\n      id\n      name\n      description\n      spaceIds\n      types {\n        id\n        name\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;