/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as base from './base/index'

export type { base }
export type { GovernancePluginsSetup } from './GovernancePluginsSetup'
export type { MainVotingPlugin } from './MainVotingPlugin'
export type { MemberAccessPlugin } from './MemberAccessPlugin'
