/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PersonalSpaceAdminCloneFactory } from './PersonalSpaceAdminCloneFactory'
export type { TestGovernancePluginsSetup } from './TestGovernancePluginsSetup'
export type { TestMemberAccessExecuteCondition } from './TestMemberAccessExecuteCondition'
export type { TestMemberAccessPlugin } from './TestMemberAccessPlugin'
export type { TestOnlyPluginUpgraderCondition } from './TestOnlyPluginUpgraderCondition'
