import { chromium } from 'playwright';
const BASE = 'https://geogenesis-git-preston-geo-3008-claim-activity-feed-geo-browser.vercel.app';
const CLAIM = '/space/41e851610e13a19441c4d980f2f2ce6b/2c61cb63c07d654b9b81ae00038befb2';
const browser = await chromium.launch({ args: ['--disable-web-security'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
await page.goto(BASE + CLAIM, { waitUntil: 'domcontentloaded', timeout: 120000 });
await page.waitForTimeout(15000);
const heading = page.getByText(/^Activity \(/).first();
await heading.scrollIntoViewIfNeeded();
await page.waitForTimeout(2500);
await page.screenshot({ path: 'activity-1.png' });
await page.mouse.wheel(0, 900);
await page.waitForTimeout(1500);
await page.screenshot({ path: 'activity-2.png' });
await browser.close();
