export const FEATURED_RANKING_ENTRIES_PER_PAGE = 5;

const FEATURED_RANKING_PAGES_TO_FETCH = 3;

export const MAX_FEATURED_RANKING_ENTRIES = FEATURED_RANKING_ENTRIES_PER_PAGE * FEATURED_RANKING_PAGES_TO_FETCH;
