/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as base from './base/index'
export { GovernancePluginsSetup__factory } from './GovernancePluginsSetup__factory'
export { MainVotingPlugin__factory } from './MainVotingPlugin__factory'
export { MemberAccessPlugin__factory } from './MemberAccessPlugin__factory'
