/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  IEditors,
  IEditorsInterface,
} from '../../../governance/base/IEditors'
import type { Provider } from '@ethersproject/providers'
import { Contract, Signer, utils } from 'ethers'

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'editor',
        type: 'address',
      },
    ],
    name: 'EditorAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'editor',
        type: 'address',
      },
    ],
    name: 'EditorRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address[]',
        name: 'editors',
        type: 'address[]',
      },
    ],
    name: 'EditorsAdded',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '_account',
        type: 'address',
      },
    ],
    name: 'isEditor',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
] as const

export class IEditors__factory {
  static readonly abi = _abi
  static createInterface(): IEditorsInterface {
    return new utils.Interface(_abi) as IEditorsInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEditors {
    return new Contract(address, _abi, signerOrProvider) as IEditors
  }
}
