/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PersonalSpaceAdminPlugin } from './PersonalSpaceAdminPlugin'
export type { PersonalSpaceAdminPluginSetup } from './PersonalSpaceAdminPluginSetup'
