/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MemberAccessExecuteCondition } from './MemberAccessExecuteCondition'
export type { OnlyPluginUpgraderCondition } from './OnlyPluginUpgraderCondition'
