export const bootstrap = [
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'KEyred99SGesjDMcbB1oD2',
      value: { type: 'TEXT', value: 'Types' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'GG8Z4cSkjv8CywbkLqVU5M',
      value: { type: 'TEXT', value: 'Name' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'LgKenoh2EfWrvqJqN6A7Ci',
      value: { type: 'TEXT', value: 'Attribute' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'DGKmqmiyVPZ7Tfe18VksjN',
      value: { type: 'TEXT', value: 'Relation Type' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'CBZs8pfSk5WHdujaAAKdD8',
      value: { type: 'TEXT', value: 'Attributes' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'VdTsW1mGiy1XSooJaBBLc4',
      value: { type: 'TEXT', value: 'Type' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'Sb7ZvdGsCDm2r1mNZBA5ft',
      value: { type: 'TEXT', value: 'Template' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'JwYkkjY2i6uuR4wrgFScwt',
      value: { type: 'TEXT', value: 'Value type' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'AKDxovGvZaPSWnmKnSoZJY',
      value: { type: 'TEXT', value: 'Relation' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'JBYTdEigecQHj2xhL3NeHV',
      value: { type: 'TEXT', value: 'Text' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'NtWv5uGJ1d15Mfk4ZdXfmU',
      value: { type: 'TEXT', value: 'Checkbox' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'Rjw5tGo76ukgvLxuYpXQkka',
      value: { type: 'TEXT', value: 'Number' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '9aNNLsQCRgFHEqRkWpd1wU',
      value: { type: 'TEXT', value: 'Point' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'WpZ6MDcJZrfheC3XD7hyhh',
      value: { type: 'TEXT', value: 'Image' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'J6cw1v8xUHCFsEdPeuB1Uo',
      value: { type: 'TEXT', value: 'Image URL' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'UGr1YqqZbE2BbEpJR9U88H',
      value: { type: 'TEXT', value: 'Date' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '5EQJAVKYDQWHZSfsawBtWa',
      value: { type: 'TEXT', value: 'Web URL' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'QoTdezDypdQrs7wq1tTRnb',
      value: { type: 'TEXT', value: 'Description' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'EXWTH2k6qquguZ8CCfMp9K',
      value: { type: 'TEXT', value: 'Space' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'GzkEQP3yedWjXE8QPFKEwV',
      value: { type: 'TEXT', value: 'Source Space' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '5jodArZNFzucsYzQaDVFBL',
      value: { type: 'TEXT', value: 'Verified Source' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'R32hqus9ojU3Twsz3HDuxf',
      value: { type: 'TEXT', value: 'Foreign Types' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '52itq1wC2HciX6gd9HEZPN',
      value: { type: 'TEXT', value: 'View' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'PnQsGwnnztrLNRCm9mcKKY',
      value: { type: 'TEXT', value: 'Data Block' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '46GzPiTRPG36jX9dmNE9ic',
      value: { type: 'TEXT', value: 'View' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'SHBs5faKV8gDeZgsUoVUQF',
      value: { type: 'TEXT', value: 'Gallery View' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'S9T1TPras3iPkVvrS5CoKE',
      value: { type: 'TEXT', value: 'Table View' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'GUKPGARFBFBMoET6NGQctJ',
      value: { type: 'TEXT', value: 'List View' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '9AecPe8JTN7uJRaX1Mk1XV',
      value: { type: 'TEXT', value: 'Shown Columns' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'Fc836HBAyTaLaZgBzcTS2a',
      value: { type: 'TEXT', value: 'Text Block' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'V6R8hWrKfLZmtyv4dQyyzo',
      value: { type: 'TEXT', value: 'Image Block' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'XbVubxtJCexLsmEhTUKPG',
      value: { type: 'TEXT', value: 'Blocks' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '3YqoLJ7uAPmthXyXmXKoSa',
      value: { type: 'TEXT', value: 'Filter' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'JiFmyuFYeoiRSiY286m7A2',
      value: { type: 'TEXT', value: 'Space filter' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'V9A2298ZHL135zFRH4qcRg',
      value: { type: 'TEXT', value: 'Markdown Content' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'ENYn2afpf2koqBfyff7CGE',
      value: { type: 'TEXT', value: 'Placeholder Image' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'AuihGk1yXCkfCcpMSwhfho',
      value: { type: 'TEXT', value: 'Placeholder Text' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'GfN9BK2oicLiBHrUavteS8',
      value: { type: 'TEXT', value: 'Person' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '399xP4sGWSoepxeEnp3UdR',
      value: { type: 'TEXT', value: 'Avatar' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'DTEcNh4xFNvsqoX9bfF6qS',
      value: { type: 'TEXT', value: 'Cover' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'VA5i7mm1v3QMjUChMT5dPs',
      value: { type: 'TEXT', value: 'Accounts' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'YCLXoVZho6C4S51g4AbF3C',
      value: { type: 'TEXT', value: 'Network' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'MuMLDVbHAmRjZQjhyk3HGx',
      value: { type: 'TEXT', value: 'Network' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'HXLpAZyQkcy6Di4YJu4xzU',
      value: { type: 'TEXT', value: 'Address' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'S7rX6suDMmU75yjbAD5WsP',
      value: { type: 'TEXT', value: 'Account' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'JnWfsCw2gqoPWFT1NXmFWW',
      value: { type: 'TEXT', value: 'Ethereum' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'CHwmK8bk4KMCqBNiV2waL9',
      value: { type: 'TEXT', value: 'Broader Spaces' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'LdAS7yWqF32E2J4doUDe5u',
      value: { type: 'TEXT', value: 'Relation Value Types' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'XAeYjgogh9zKBz4g8pB9wG',
      value: { type: 'TEXT', value: 'Relation' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'gEfvT3cW16tyPmFEGA9bp',
      value: { type: 'TEXT', value: 'Index' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'NToMyNnNkCvFh1McQLm4Rm',
      value: { type: 'TEXT', value: 'To entity' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '3ZZFJ1dDBk7zTvN5x3XRR3',
      value: { type: 'TEXT', value: 'From entity' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'J8nmVHZDeCLNhPxX7qyEZG',
      value: { type: 'TEXT', value: 'Data Source' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '4sz7Kx91uq4KBW5sohjLkj',
      value: { type: 'TEXT', value: 'Data Source Type' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '3J6223VX6MkwTftWdzDfo4',
      value: { type: 'TEXT', value: 'Collection Data Source' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'XqDkiYjqEufsbjqegxkqZU',
      value: { type: 'TEXT', value: 'Geo Data Source' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '8HkP7HCufp2HcCFajuJFcq',
      value: { type: 'TEXT', value: 'Query Data Source' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'Mwrn46KavwfWgNrFaWcB9j',
      value: { type: 'TEXT', value: 'Collection Item' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'RemzN69c24othsp2rP7yMX',
      value: { type: 'TEXT', value: 'Nonprofit' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '9vk7Q3pz7US3s2KePFQrJT',
      value: { type: 'TEXT', value: 'Project' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'UhpHYoFEzAov9WwqtDwQk4',
      value: { type: 'TEXT', value: 'Company' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '9u4zseS3EDXG9ZvwR9RmqU',
      value: { type: 'TEXT', value: 'Page' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'DD9FKRZ3XezaKEGUszMB3r',
      value: { type: 'TEXT', value: 'Page type' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'E3jboNrTeuopjKgJ45ykBd',
      value: { type: 'TEXT', value: 'Posts page' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '3scJVFciFuhmaXe852pT3F',
      value: { type: 'TEXT', value: 'Projects page' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'R6FDYEK9CCdEQuxjuRjA2U',
      value: { type: 'TEXT', value: 'Finances page' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'BWMHGbpR31xTbjvk4QZdQA',
      value: { type: 'TEXT', value: 'Team page' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'PJzxY3isAL3hGx1bRkYdPf',
      value: { type: 'TEXT', value: 'Jobs page' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'K97FaTqrx54jdiM93vZ1Fc',
      value: { type: 'TEXT', value: 'Events page' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '2V8pajmGDJt8egodkJeoPC',
      value: { type: 'TEXT', value: 'Services page' },
    },
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'Cnf53HgY8T7Fwcq8choaRn',
      value: { type: 'TEXT', value: 'Products page' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'AdkdkeGVhZ9ToMEQig2jR6',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'KEyred99SGesjDMcbB1oD2',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'B4ESZepzUVNRrDgWkXpiHs',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'Sb7ZvdGsCDm2r1mNZBA5ft',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'LjtYGRrskCnNSgyigQZhHd',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'CBZs8pfSk5WHdujaAAKdD8',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '7oWRBeKkHrdcDk1rLLUscd',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'DGKmqmiyVPZ7Tfe18VksjN',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'RfYNxB37iXGqLs5hjLL2N8',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'JwYkkjY2i6uuR4wrgFScwt',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '4wsDEJYb9gGoyvC9xAeC4K',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'QoTdezDypdQrs7wq1tTRnb',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Defuv99CHNQXU2ZmHRkqRg',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'GG8Z4cSkjv8CywbkLqVU5M',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'UUuaHJkqA8KfY3GRh3TZn4',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'GzkEQP3yedWjXE8QPFKEwV',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'VVXLEQxaJTkwYigrqceRYS',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '5jodArZNFzucsYzQaDVFBL',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'EpmDHTqNkdtaKd5pwD8t7x',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '46GzPiTRPG36jX9dmNE9ic',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'AZKYZVHfoNDNoEb63BGS24',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'R32hqus9ojU3Twsz3HDuxf',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Fv38P7G5kNVNTFJCqqctdk',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'V9A2298ZHL135zFRH4qcRg',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'XGsxbJGcA2Ge6gwef5gdF3',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'XbVubxtJCexLsmEhTUKPG',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'TySvXEkVMLphBVmBDK7uNX',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '3YqoLJ7uAPmthXyXmXKoSa',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'YHDBzUMmuEuXc25AQ267vH',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'ENYn2afpf2koqBfyff7CGE',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '44kQAciLeThBb8Q6p6Ye2y',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'AuihGk1yXCkfCcpMSwhfho',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'DUvDDRxXomHYVRH5HJmwBz',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'LdAS7yWqF32E2J4doUDe5u',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'VGvuDXsgxXkXQWmWjLKvRz',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'gEfvT3cW16tyPmFEGA9bp',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8CSLSNUfmQ8LUcDA2eWjLT',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'NToMyNnNkCvFh1McQLm4Rm',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'MfJFrC2AaNs4gxucqoESn3',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '3ZZFJ1dDBk7zTvN5x3XRR3',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'H1XAZEKxXDiczDfyYez8Fe',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'J6cw1v8xUHCFsEdPeuB1Uo',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'QaCj9NiUFPNGuPZ2iWFV3H',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'CHwmK8bk4KMCqBNiV2waL9',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'CGQPp7VhbTrUDAV3uA1Ps4',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '4sz7Kx91uq4KBW5sohjLkj',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '2YjbrAsPStqQQ4HcCffN46',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'J8nmVHZDeCLNhPxX7qyEZG',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '4yGu5FgM4pyWK7iWD5mVMw',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'Mwrn46KavwfWgNrFaWcB9j',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'CHVnQJWpXoCS453bbtGg3V',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '7gQe68xfXDYGaCBqK7Rxjg',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '399xP4sGWSoepxeEnp3UdR',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'BxVNRATjJ2YoAoRKmXcpuP',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'DTEcNh4xFNvsqoX9bfF6qS',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'TVVb5MWoTwLLGA25aYktuz',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'VA5i7mm1v3QMjUChMT5dPs',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'FhLjSVwNoZK3uCsRiUG418',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'MuMLDVbHAmRjZQjhyk3HGx',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '7g9Qwnr8XR8ptcB5rrXeEs',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'HXLpAZyQkcy6Di4YJu4xzU',
      toEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'L1G1gtL8WUFpBwh6dfJpU5',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'KEyred99SGesjDMcbB1oD2',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Vii2ewz5GaA8xoMnADByoW',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'Sb7ZvdGsCDm2r1mNZBA5ft',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'W38ZQ2EfcZA6h3QawmwbQt',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'CBZs8pfSk5WHdujaAAKdD8',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '326rUCiZurStLkyddUw2zP',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'DGKmqmiyVPZ7Tfe18VksjN',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '5yVuMVeoRC4sYTRwt1qYgG',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'JwYkkjY2i6uuR4wrgFScwt',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '4pUxGrYBiXjkqhoKmXn4hx',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'QoTdezDypdQrs7wq1tTRnb',
      toEntity: 'JBYTdEigecQHj2xhL3NeHV',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'McLWXEUkXuFy4C4BNnnTF3',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'GG8Z4cSkjv8CywbkLqVU5M',
      toEntity: 'JBYTdEigecQHj2xhL3NeHV',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'X28pBN14QqqmpcidCo9Ppo',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'GzkEQP3yedWjXE8QPFKEwV',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Ko1gjp87PJ8QJooRjEWrAP',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: '5jodArZNFzucsYzQaDVFBL',
      toEntity: 'NtWv5uGJ1d15Mfk4ZdXfmU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '5aVCHWJLTyfRUdmNe9b5KE',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: '46GzPiTRPG36jX9dmNE9ic',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'EQXRcPb6mfxBjC7eKvgbn3',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'R32hqus9ojU3Twsz3HDuxf',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'DR1WCp6EGLZiASETEjh7f3',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'V9A2298ZHL135zFRH4qcRg',
      toEntity: 'JBYTdEigecQHj2xhL3NeHV',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '6qnU1g9fWXNA4oamxPmbML',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'XbVubxtJCexLsmEhTUKPG',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '3PeWoYLE1Lt3GDBGTVY77J',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: '3YqoLJ7uAPmthXyXmXKoSa',
      toEntity: 'JBYTdEigecQHj2xhL3NeHV',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Q4rjAtMqSnmcWH1WWLk7PY',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'ENYn2afpf2koqBfyff7CGE',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'U2HHDL8QB67uwAp6ohGkxC',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'AuihGk1yXCkfCcpMSwhfho',
      toEntity: 'JBYTdEigecQHj2xhL3NeHV',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'PoBDFzcNfVkZwk5w5E2vyw',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'LdAS7yWqF32E2J4doUDe5u',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'FKfqk4giog5nC5eEEMNMeX',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'gEfvT3cW16tyPmFEGA9bp',
      toEntity: 'JBYTdEigecQHj2xhL3NeHV',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'LFEFpNvDkvGUfCfj6YoCmr',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'NToMyNnNkCvFh1McQLm4Rm',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'C95Lf7FSXJxaCYH5DYe6MR',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: '3ZZFJ1dDBk7zTvN5x3XRR3',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'EVnS1aUv49gLDnNPdy1fwc',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'J6cw1v8xUHCFsEdPeuB1Uo',
      toEntity: '5EQJAVKYDQWHZSfsawBtWa',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'MHUoRxB3UdRB13AikcvngN',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'CHwmK8bk4KMCqBNiV2waL9',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'QhLxiPdfYwkB2jM4zn1p2x',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: '4sz7Kx91uq4KBW5sohjLkj',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'BnTp5BX2UAhUFP4FW5tGoC',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'J8nmVHZDeCLNhPxX7qyEZG',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8rGNRBXDwF2fzFAGsF6FeM',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'Mwrn46KavwfWgNrFaWcB9j',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '24jEFvdfenaauQV8Hudy4N',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '3zybGZGSP53DvdPwFW5XrD',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: '399xP4sGWSoepxeEnp3UdR',
      toEntity: 'X8KB1uF84RYppghBSVvhqr',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'JnKLsJw5r18Pmw2BW4y3UT',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'DTEcNh4xFNvsqoX9bfF6qS',
      toEntity: 'X8KB1uF84RYppghBSVvhqr',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'M5siULoKmGh7W7stMYmgRQ',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'VA5i7mm1v3QMjUChMT5dPs',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'PQjKzTVaYGoY1o2qYX1dk5',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'MuMLDVbHAmRjZQjhyk3HGx',
      toEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '65mgbWd7SNSrdcWwHY2hvC',
      type: 'JwYkkjY2i6uuR4wrgFScwt',
      fromEntity: 'HXLpAZyQkcy6Di4YJu4xzU',
      toEntity: 'JBYTdEigecQHj2xhL3NeHV',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'UUCdHExH7wePmSd9rSpvfi',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'NxW24j7PBwi1S59WYjo51Z',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '52itq1wC2HciX6gd9HEZPN',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'TnTyYdgUbirPK4uKjP5ogG',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'JBYTdEigecQHj2xhL3NeHV',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '3t8Xm1YU9GyGP1vxphunRr',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'Rjw5tGo76ukgvLxuYpXQkka',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '6WoDbF3GTX977tpLamtNE4',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '9aNNLsQCRgFHEqRkWpd1wU',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'AJmHLYnEoS2Jv7whqePCbw',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'NtWv5uGJ1d15Mfk4ZdXfmU',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'JMcssoV6FBWVkX8GAboBPU',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'AKDxovGvZaPSWnmKnSoZJY',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'GWnVtEXKr1F9QvpF1NfD6R',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'WpZ6MDcJZrfheC3XD7hyhh',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '6LSbMfe1NP9mpVUxHSALYU',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'UGr1YqqZbE2BbEpJR9U88H',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '5KznEVTwN3LUoXvhmgLkGx',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '5EQJAVKYDQWHZSfsawBtWa',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '3oeW9PnBLsqp7VFCzEYSG9',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '2bTq4EAxvzQN7NuaE6oM2B',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'EXWTH2k6qquguZ8CCfMp9K',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Qt3gLJSBdqMZsy9nXbWekM',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'V6R8hWrKfLZmtyv4dQyyzo',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'hmdxDMcPQMthQbib7MR5i',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'RRDZHoRKL3fA9DJKaFRZfv',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'Fc836HBAyTaLaZgBzcTS2a',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'MBNAKPP3dQmkJuAtho3nKF',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'GfN9BK2oicLiBHrUavteS8',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '9ptb79rCWuEBXHJq1ZV5Sk',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'S7rX6suDMmU75yjbAD5WsP',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8A18DRTChzNCvHN1ouCyBe',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'YCLXoVZho6C4S51g4AbF3C',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Mu9qkJ1hrGK2Qp8oMScMYS',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'RemzN69c24othsp2rP7yMX',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Q1uwPZ8Ufgp3Fk9RoaUboH',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '9vk7Q3pz7US3s2KePFQrJT',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '79wMge111yP3dYJzbwxcE',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'UhpHYoFEzAov9WwqtDwQk4',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'TiQ4fkHuNwUGVQhdoivzNa',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'XAeYjgogh9zKBz4g8pB9wG',
      toEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'EGgGUBXEAuFCW2qhfNVRZf',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'VdTsW1mGiy1XSooJaBBLc4',
      toEntity: 'Sb7ZvdGsCDm2r1mNZBA5ft',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'PrnMty7Mhy6gua5eq9QHHX',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'WpZ6MDcJZrfheC3XD7hyhh',
      toEntity: 'J6cw1v8xUHCFsEdPeuB1Uo',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'U4Fzg5mDxhUoTdtafMUsME',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'LgKenoh2EfWrvqJqN6A7Ci',
      toEntity: 'JwYkkjY2i6uuR4wrgFScwt',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8oUrUuBSYBgsDinn2U9Vpx',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'EXWTH2k6qquguZ8CCfMp9K',
      toEntity: 'R32hqus9ojU3Twsz3HDuxf',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8GbLSKgLChwBYGkFCEj6Hn',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'EXWTH2k6qquguZ8CCfMp9K',
      toEntity: 'XbVubxtJCexLsmEhTUKPG',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'YX6iLyuKMRm4qFx8C3C6Kg',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'V6R8hWrKfLZmtyv4dQyyzo',
      toEntity: 'J6cw1v8xUHCFsEdPeuB1Uo',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '6XyvesXT5xNui1pt7ReoKp',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'Fc836HBAyTaLaZgBzcTS2a',
      toEntity: 'V9A2298ZHL135zFRH4qcRg',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'RHutdpTLVwmYGJph7qd2cM',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'GfN9BK2oicLiBHrUavteS8',
      toEntity: '399xP4sGWSoepxeEnp3UdR',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '2iJpG5MXfxxx2YQguW4UBV',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'GfN9BK2oicLiBHrUavteS8',
      toEntity: 'DTEcNh4xFNvsqoX9bfF6qS',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'CQBUKhGF4iYcViF3jLJ7yM',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'S7rX6suDMmU75yjbAD5WsP',
      toEntity: 'MuMLDVbHAmRjZQjhyk3HGx',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '4tiRsJahyK8aKT36t2xSBi',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'S7rX6suDMmU75yjbAD5WsP',
      toEntity: 'HXLpAZyQkcy6Di4YJu4xzU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '6yJZT12WJ2rdK2DLUFhqsj',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'XAeYjgogh9zKBz4g8pB9wG',
      toEntity: 'gEfvT3cW16tyPmFEGA9bp',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'UF8Ca3TbyxeQtHSwKrVxWJ',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'XAeYjgogh9zKBz4g8pB9wG',
      toEntity: 'NToMyNnNkCvFh1McQLm4Rm',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '5ipRfdbxUMpAXTxAY4wTts',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'XAeYjgogh9zKBz4g8pB9wG',
      toEntity: '3ZZFJ1dDBk7zTvN5x3XRR3',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'MetXUBnJ7epscN2HMNA5MQ',
      type: 'CBZs8pfSk5WHdujaAAKdD8',
      fromEntity: 'XAeYjgogh9zKBz4g8pB9wG',
      toEntity: 'DGKmqmiyVPZ7Tfe18VksjN',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'HEuj9VYAF5z1KQ8x37Uzze',
      value: { type: 'TEXT', value: 'Nonprofit Space Configuration Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'VqEqNDaV2fCfzWZubitdUE',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'HEuj9VYAF5z1KQ8x37Uzze',
      toEntity: 'RemzN69c24othsp2rP7yMX',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'FBT3Bt5nvFqPEUuwqgVzyE',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'HEuj9VYAF5z1KQ8x37Uzze',
      toEntity: '9vk7Q3pz7US3s2KePFQrJT',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'LzNFMjpk7qaTNu6DHUiq3H',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'HEuj9VYAF5z1KQ8x37Uzze',
      toEntity: 'EXWTH2k6qquguZ8CCfMp9K',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '9V1Z6BHBcZ4Y2QmNVwkH8c',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '9vxxUcLM8uxjCoUuPc1gWe',
      toEntity: 'Fc836HBAyTaLaZgBzcTS2a',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'V9A2298ZHL135zFRH4qcRg',
      entity: '9vxxUcLM8uxjCoUuPc1gWe',
      value: { type: 'TEXT', value: '## Welcome to our nonprofit!' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Fiszyfjm5mwXKq3D5vGxA8',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'HEuj9VYAF5z1KQ8x37Uzze',
      toEntity: '9vxxUcLM8uxjCoUuPc1gWe',
      index: 'NQfjQhIi.D',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'NJN1qs6AUQDhyo5rBF2yjD',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'PmmAm79YtQv9gNGpCkrH3N',
      toEntity: 'Fc836HBAyTaLaZgBzcTS2a',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'V9A2298ZHL135zFRH4qcRg',
      entity: 'PmmAm79YtQv9gNGpCkrH3N',
      value: {
        type: 'TEXT',
        value:
          "We're thrilled to have you here. At our core, we are driven by a passionate commitment to positive change. As a community, we believe in the power of collective action to make a difference, no matter how big or small. Together, we can create meaningful impact and contribute to a better world. Thank you for joining us on this journey towards a brighter future.",
      },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'VQQHcZhsTGmXBUGeHUvnLt',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'HEuj9VYAF5z1KQ8x37Uzze',
      toEntity: 'PmmAm79YtQv9gNGpCkrH3N',
      index: 'NQfjQhIi.F',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'G8iePrDZk2SkqL9QEW6nCR',
      value: { type: 'TEXT', value: 'Nonprofit Posts Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'TDtSRJ3DM8GpY98JAZxb16',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'G8iePrDZk2SkqL9QEW6nCR',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8U7cCWqe1wJkDWtpuF2Xd8',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'RnRkvZTVBGuVbRPmWHJokw',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Fwiv2jaR9YmEhY2cepAHau',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'RnRkvZTVBGuVbRPmWHJokw',
      toEntity: 'XqDkiYjqEufsbjqegxkqZU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8qa8CM1rmZk4rQdMK69yV2',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'G8iePrDZk2SkqL9QEW6nCR',
      toEntity: 'RnRkvZTVBGuVbRPmWHJokw',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'RnRkvZTVBGuVbRPmWHJokw',
      value: { type: 'TEXT', value: 'Posts' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'QmTGgt6mxQzH1KRwJK922y',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: 'G8iePrDZk2SkqL9QEW6nCR',
      toEntity: 'E3jboNrTeuopjKgJ45ykBd',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'JkJDTY4f3Xc6APZKna5kGh',
      value: { type: 'TEXT', value: 'Nonprofit Projects Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'VKh1gUWXGbX14WPRvrfF4b',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'JkJDTY4f3Xc6APZKna5kGh',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'GWNF3SBTYeCfZN8yyN8Kyu',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '6NmPcCeNc15XoUL6k7oWdu',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'JV7emPUmhteMJ6zo9CWFsD',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: '6NmPcCeNc15XoUL6k7oWdu',
      toEntity: 'XqDkiYjqEufsbjqegxkqZU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '5mgsxXPTpbXes5iTApbJHm',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'JkJDTY4f3Xc6APZKna5kGh',
      toEntity: '6NmPcCeNc15XoUL6k7oWdu',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '6NmPcCeNc15XoUL6k7oWdu',
      value: { type: 'TEXT', value: 'Projects' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'X97HsHTNxWyCDRqK6vdL5M',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: 'JkJDTY4f3Xc6APZKna5kGh',
      toEntity: '3scJVFciFuhmaXe852pT3F',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'K51CbDqxW35osbjPo5ZF77',
      value: { type: 'TEXT', value: 'Nonprofit Team Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'DPtq5nXqmpN4vEbtsSdcNk',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'K51CbDqxW35osbjPo5ZF77',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '5GqXbQ63T9YHkuTBchqzfe',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'DiaxMrAhLoGUFCq1mNNgoG',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'D7kosmkYcEDrsowJLm9g3Q',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'DiaxMrAhLoGUFCq1mNNgoG',
      toEntity: '3J6223VX6MkwTftWdzDfo4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'XUsAVKXoGpE7jE8pjv6kyq',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'K51CbDqxW35osbjPo5ZF77',
      toEntity: 'DiaxMrAhLoGUFCq1mNNgoG',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'DiaxMrAhLoGUFCq1mNNgoG',
      value: { type: 'TEXT', value: 'Projects' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Vpo7GCThLryQcYgsJ3aVic',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: 'K51CbDqxW35osbjPo5ZF77',
      toEntity: '3scJVFciFuhmaXe852pT3F',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'G3PRyzNzRNWn4m7S4sESQG',
      value: { type: 'TEXT', value: 'Nonprofit Finances Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'KkbpQPMLvjtj8TUi7Mx6N6',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'G3PRyzNzRNWn4m7S4sESQG',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'XBzXpLHtjdu6UMz6n9jhUR',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'FL2yCDjRwkQ6dUPMNqqZEE',
      toEntity: 'Fc836HBAyTaLaZgBzcTS2a',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'V9A2298ZHL135zFRH4qcRg',
      entity: 'FL2yCDjRwkQ6dUPMNqqZEE',
      value: { type: 'TEXT', value: 'Welcome to the finance summary of this nonprofit.' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'H4kVkD1EsEf5rH5GTmg8i9',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'G3PRyzNzRNWn4m7S4sESQG',
      toEntity: 'FL2yCDjRwkQ6dUPMNqqZEE',
      index: 'NQfjQhIi.D',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'XCZHsd6fqhsBm3x9vwdk6B',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'QYHcUHTCcFRdFu1N7EK3Yx',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '4dN2bvvNrXRnQx3gchAwip',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'QYHcUHTCcFRdFu1N7EK3Yx',
      toEntity: 'XqDkiYjqEufsbjqegxkqZU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'K8d9XLLB2ezNwiK97RsDyT',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'G3PRyzNzRNWn4m7S4sESQG',
      toEntity: 'QYHcUHTCcFRdFu1N7EK3Yx',
      index: 'NQfjQhIi.F',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'QYHcUHTCcFRdFu1N7EK3Yx',
      value: { type: 'TEXT', value: 'Finance Summaries' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8jMMGZimYuNVnBX6218WfX',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: 'G3PRyzNzRNWn4m7S4sESQG',
      toEntity: 'R6FDYEK9CCdEQuxjuRjA2U',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'QZwChwTixtbLDv3HSX5E6n',
      value: { type: 'TEXT', value: 'Company Space Configuration Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8tRS98xH9vjzLBnrJ4Xxr3',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'QZwChwTixtbLDv3HSX5E6n',
      toEntity: 'EXWTH2k6qquguZ8CCfMp9K',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'NgdoYEWQF1Y2NBMkG4NxkS',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'QZwChwTixtbLDv3HSX5E6n',
      toEntity: 'UhpHYoFEzAov9WwqtDwQk4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8bPrh8tUby5uY5dckMa7Mu',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'UnCgzKfdfAZd9qfE3dHNoD',
      toEntity: 'Fc836HBAyTaLaZgBzcTS2a',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'V9A2298ZHL135zFRH4qcRg',
      entity: 'UnCgzKfdfAZd9qfE3dHNoD',
      value: { type: 'TEXT', value: '## Welcome to our company!' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'RbAJacLqnJfqQJR8RL4ZPL',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'QZwChwTixtbLDv3HSX5E6n',
      toEntity: 'UnCgzKfdfAZd9qfE3dHNoD',
      index: 'NQfjQhIi.D',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '4822yf1BB7ovNQqoY4LH1r',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'SqybFAMxRYZbjpRkc9sdwc',
      toEntity: 'Fc836HBAyTaLaZgBzcTS2a',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'V9A2298ZHL135zFRH4qcRg',
      entity: 'SqybFAMxRYZbjpRkc9sdwc',
      value: {
        type: 'TEXT',
        value:
          "We're dedicated to pushing boundaries and fostering innovation. With a focus on excellence and a passion for progress, we strive to make a positive impact in everything we do. From our talented team to our cutting-edge solutions, we're committed to delivering unparalleled quality and service to our customers.",
      },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '5U6Z1ijVULCQJ55GugiRo6',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'QZwChwTixtbLDv3HSX5E6n',
      toEntity: 'SqybFAMxRYZbjpRkc9sdwc',
      index: 'NQfjQhIi.F',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'KzJ2DA827jxioxgjwiySp5',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '6iGMJnPQAp8ZJ46jraCasw',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'UgbaK3djXpZX5xmyfzgBXa',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: '6iGMJnPQAp8ZJ46jraCasw',
      toEntity: '3J6223VX6MkwTftWdzDfo4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Mbmf1iXx65t1yZygvHT3si',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'QZwChwTixtbLDv3HSX5E6n',
      toEntity: '6iGMJnPQAp8ZJ46jraCasw',
      index: 'NQfjQhIi.H',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '6iGMJnPQAp8ZJ46jraCasw',
      value: { type: 'TEXT', value: 'Goals' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'AHLknvNrbs7CBao2i58mo5',
      value: { type: 'TEXT', value: 'Company Posts Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'E2335BaoSEGDZbGTaDNfGf',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'AHLknvNrbs7CBao2i58mo5',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '2ScMcn352x6TtorRt4c3dh',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'D1tpXTPxDQWAHRzHm7jUZN',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'WtAs7zRPXMD5iQcTK23wbd',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'D1tpXTPxDQWAHRzHm7jUZN',
      toEntity: 'XqDkiYjqEufsbjqegxkqZU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Mj7no86aHHFbf94WKKs62b',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'AHLknvNrbs7CBao2i58mo5',
      toEntity: 'D1tpXTPxDQWAHRzHm7jUZN',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'D1tpXTPxDQWAHRzHm7jUZN',
      value: { type: 'TEXT', value: 'Posts' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '3bfEmhZuMwdXrD8AZsuRnM',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: 'AHLknvNrbs7CBao2i58mo5',
      toEntity: 'E3jboNrTeuopjKgJ45ykBd',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '4CTRE9hBWqb7CjiaxQx47C',
      value: { type: 'TEXT', value: 'Company Events Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'SupBvfiajY5MiTAGAhxFvk',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '4CTRE9hBWqb7CjiaxQx47C',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '8JW5bGtBRErsyue4B9aYcw',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'EaxXevmBF8gqbrmeqQooKv',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'B1TRXmbfKPWdJFnGsT1szx',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'EaxXevmBF8gqbrmeqQooKv',
      toEntity: 'XqDkiYjqEufsbjqegxkqZU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'P5UjmPT3QNwb1wkWGC1cyZ',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: '4CTRE9hBWqb7CjiaxQx47C',
      toEntity: 'EaxXevmBF8gqbrmeqQooKv',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'EaxXevmBF8gqbrmeqQooKv',
      value: { type: 'TEXT', value: 'Events' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'B7yGe3ZugoPcrLQnui3Gqk',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: '4CTRE9hBWqb7CjiaxQx47C',
      toEntity: 'K97FaTqrx54jdiM93vZ1Fc',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'DSANGC24exwsRWXrfikKb7',
      value: { type: 'TEXT', value: 'Company Jobs Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'dqYvV8MguGRz43MJMDWLa',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'DSANGC24exwsRWXrfikKb7',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'GiEqReqddm7UuZHKgcu9b3',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'W1hD1ZaDhVp6jKFtpvbJ7u',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Y9hq4i4NCgBU4xJ9KhaW6P',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'W1hD1ZaDhVp6jKFtpvbJ7u',
      toEntity: 'XqDkiYjqEufsbjqegxkqZU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '4m53UZqXdJ8xHcLAU9DNRg',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'DSANGC24exwsRWXrfikKb7',
      toEntity: 'W1hD1ZaDhVp6jKFtpvbJ7u',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'W1hD1ZaDhVp6jKFtpvbJ7u',
      value: { type: 'TEXT', value: 'Job openings' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '4ZzTDynR7jje2dfxMoKVkc',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: 'DSANGC24exwsRWXrfikKb7',
      toEntity: 'PJzxY3isAL3hGx1bRkYdPf',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '7Dp2MBb1tjMk6igDaYTZtb',
      value: { type: 'TEXT', value: 'Company Products Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'A3ZVWwznNVSuHN2j87cDq2',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '7Dp2MBb1tjMk6igDaYTZtb',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '6rF2LBPe8nMsZAg8fRzRw4',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'A4FNc9pZuhKm56XZLvmTbU',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'PZTCm4LbTLaCTTWs38dBZ7',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'A4FNc9pZuhKm56XZLvmTbU',
      toEntity: 'XqDkiYjqEufsbjqegxkqZU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Q3Ttt73kc4E9G3UzCg3hza',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: '7Dp2MBb1tjMk6igDaYTZtb',
      toEntity: 'A4FNc9pZuhKm56XZLvmTbU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'A4FNc9pZuhKm56XZLvmTbU',
      value: { type: 'TEXT', value: 'Products' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'FisakiJ7xjrSxhoHJUGdwu',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: '7Dp2MBb1tjMk6igDaYTZtb',
      toEntity: 'Cnf53HgY8T7Fwcq8choaRn',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'NRLUry4uMctKx6yiC2GP9F',
      value: { type: 'TEXT', value: 'Company Services Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'EspkjHjvtzeGv3S92qEFTK',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'NRLUry4uMctKx6yiC2GP9F',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'REpG17b5ikKk82nDE5xtgH',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'N9gbYHjSc1hzirVbeA4Hfa',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'WpHq2brn1A4bsb63ZuYWjq',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'N9gbYHjSc1hzirVbeA4Hfa',
      toEntity: 'XqDkiYjqEufsbjqegxkqZU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'P7HDAJvRxgSSCTMFyHd93r',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'NRLUry4uMctKx6yiC2GP9F',
      toEntity: 'N9gbYHjSc1hzirVbeA4Hfa',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'N9gbYHjSc1hzirVbeA4Hfa',
      value: { type: 'TEXT', value: 'Services' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '9H3XTLP3JeytrgaUz4i6gw',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: 'NRLUry4uMctKx6yiC2GP9F',
      toEntity: '2V8pajmGDJt8egodkJeoPC',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'B59SUroy7uy9yCHF9AD9mP',
      value: { type: 'TEXT', value: 'Company Team Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'AV1EJYNodEfu4Yj7qG9XXM',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'B59SUroy7uy9yCHF9AD9mP',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'NUo3s4MLbPbQYsXC2j82TJ',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'FBWQEwJv8F8SVRnXnZuGVY',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'GdPy4zL2iiSqwDZCv5fNeM',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'FBWQEwJv8F8SVRnXnZuGVY',
      toEntity: '3J6223VX6MkwTftWdzDfo4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '973vkg8XAjQPvKNkKkHgwx',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'B59SUroy7uy9yCHF9AD9mP',
      toEntity: 'FBWQEwJv8F8SVRnXnZuGVY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'FBWQEwJv8F8SVRnXnZuGVY',
      value: { type: 'TEXT', value: 'Team members' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'TyxQwpnaLSExaM4dqwYnvL',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: 'B59SUroy7uy9yCHF9AD9mP',
      toEntity: 'BWMHGbpR31xTbjvk4QZdQA',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'EJuFuEz17wdVCk9ctEAkW7',
      value: { type: 'TEXT', value: 'Person Space Configuration Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'AkPSTiqMDJ5UUvyF5V2ncu',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'EJuFuEz17wdVCk9ctEAkW7',
      toEntity: 'EXWTH2k6qquguZ8CCfMp9K',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '4HrA4ag5tna2HF75MVtxbq',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'EJuFuEz17wdVCk9ctEAkW7',
      toEntity: 'GfN9BK2oicLiBHrUavteS8',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'TSDR2UYwSzArPqNcoTirCR',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '84mJPmYEgmUYtTGDXtqYtj',
      toEntity: 'Fc836HBAyTaLaZgBzcTS2a',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'V9A2298ZHL135zFRH4qcRg',
      entity: '84mJPmYEgmUYtTGDXtqYtj',
      value: { type: 'TEXT', value: '## Welcome to my personal space' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'dwUhM1spxi8fzF74d2SpU',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'EJuFuEz17wdVCk9ctEAkW7',
      toEntity: '84mJPmYEgmUYtTGDXtqYtj',
      index: 'NQfjQhIi.D',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Pptn3phRWS1brDSGGXVnUj',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'SBMPjYAqMQs9mXNFYTHc9B',
      toEntity: 'Fc836HBAyTaLaZgBzcTS2a',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'V9A2298ZHL135zFRH4qcRg',
      entity: 'SBMPjYAqMQs9mXNFYTHc9B',
      value: {
        type: 'TEXT',
        value:
          "This space is where I compile my interests, posts, collections, and a summary of myself, along with anything else I'd like to share with the broader Geo community.",
      },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'WR2xYE8V7JeBmP9ytzNLxw',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'EJuFuEz17wdVCk9ctEAkW7',
      toEntity: 'SBMPjYAqMQs9mXNFYTHc9B',
      index: 'NQfjQhIi.F',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'ATz89N953SasdTFMHLWKtK',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'RRWe9bq3afzmW6owwNWRLB',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'SUspig7HK4knnmWXE9H1pp',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'RRWe9bq3afzmW6owwNWRLB',
      toEntity: '3J6223VX6MkwTftWdzDfo4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'FBu2JdNJDniQsfH8ibECfE',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'EJuFuEz17wdVCk9ctEAkW7',
      toEntity: 'RRWe9bq3afzmW6owwNWRLB',
      index: 'NQfjQhIi.H',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'RRWe9bq3afzmW6owwNWRLB',
      value: { type: 'TEXT', value: 'Goals' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'JbMuXG61dERphd4YiLXdeM',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'R6f92TWXjhKgn8p67Z7D2',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'Qwotu1AqXyV3mitNWRGZqt',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'R6f92TWXjhKgn8p67Z7D2',
      toEntity: '3J6223VX6MkwTftWdzDfo4',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'TZ7qquVRete7mJ2tEv7Erz',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: 'EJuFuEz17wdVCk9ctEAkW7',
      toEntity: 'R6f92TWXjhKgn8p67Z7D2',
      index: 'NQfjQhIi.J',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'R6f92TWXjhKgn8p67Z7D2',
      value: { type: 'TEXT', value: 'Skills' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: '98wgvodwzidmVA4ryVzGX6',
      value: { type: 'TEXT', value: 'Person Posts Page Template' },
    },
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'NpFPisHP2LE825RyFSpEnJ',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: '98wgvodwzidmVA4ryVzGX6',
      toEntity: '9u4zseS3EDXG9ZvwR9RmqU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '98BKrGmLu6AoJAwtgKJ2Qb',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'Puf91doVAANL59Mep2siie',
      toEntity: 'PnQsGwnnztrLNRCm9mcKKY',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'R4ZXJpNMkKZe7Nx6haSZgf',
      type: '4sz7Kx91uq4KBW5sohjLkj',
      fromEntity: 'Puf91doVAANL59Mep2siie',
      toEntity: 'XqDkiYjqEufsbjqegxkqZU',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: 'RMuWKRrdCw22d27wuVNQCC',
      type: 'XbVubxtJCexLsmEhTUKPG',
      fromEntity: '98wgvodwzidmVA4ryVzGX6',
      toEntity: 'Puf91doVAANL59Mep2siie',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'SET_TRIPLE',
    triple: {
      attribute: 'GG8Z4cSkjv8CywbkLqVU5M',
      entity: 'Puf91doVAANL59Mep2siie',
      value: { type: 'TEXT', value: 'Posts' },
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '7Jf9KvrMxFBujGAP9eAfVa',
      type: 'DD9FKRZ3XezaKEGUszMB3r',
      fromEntity: '98wgvodwzidmVA4ryVzGX6',
      toEntity: 'E3jboNrTeuopjKgJ45ykBd',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
  {
    type: 'CREATE_RELATION',
    relation: {
      id: '5MdLWmz1jZVPdtmiKEJNcU',
      type: 'KEyred99SGesjDMcbB1oD2',
      fromEntity: 'JnWfsCw2gqoPWFT1NXmFWW',
      toEntity: 'YCLXoVZho6C4S51g4AbF3C',
      index: 'NQfjQhIi.B',
    },
    space: 'BJqiLPcSgfF8FRxkFr76Uy',
  },
];
