/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PersonalSpaceAdminPlugin__factory } from './PersonalSpaceAdminPlugin__factory'
export { PersonalSpaceAdminPluginSetup__factory } from './PersonalSpaceAdminPluginSetup__factory'
