/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Addresslist } from './Addresslist'
export type { IEditors } from './IEditors'
export type { IMembers } from './IMembers'
export type { IMultisig } from './IMultisig'
export type { MajorityVotingBase } from './MajorityVotingBase'
