import { describe, expect, it } from 'vitest';

import { generateTriplesForNonprofit } from './generate-triples-for-nonprofit';

describe('Generating triples in a nonprofit space', () => {
  it('generates initial content template', () => {
    expect(
      generateTriplesForNonprofit('MOCK_SPACE_CONFIG_ENTITY_ID', 'MOCK_SPACE_NAME', 'MOCK_SPACE_ADDRESS')
    ).toMatchInlineSnapshot([
      {
        attributeId: 'be745973-05a9-4cd0-a46d-1c5538270faf',
        attributeName: 'Foreign Types',
        entityId: expect.any(String),
        entityName: 'MOCK_SPACE_NAME',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Page',
          type: 'entity',
        },
      },
      {
        attributeId: 'be745973-05a9-4cd0-a46d-1c5538270faf',
        attributeName: 'Foreign Types',
        entityId: expect.any(String),
        entityName: 'MOCK_SPACE_NAME',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Tag',
          type: 'entity',
        },
      },
      {
        attributeId: 'be745973-05a9-4cd0-a46d-1c5538270faf',
        attributeName: 'Foreign Types',
        entityId: expect.any(String),
        entityName: 'MOCK_SPACE_NAME',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Post',
          type: 'entity',
        },
      },
      {
        attributeId: 'be745973-05a9-4cd0-a46d-1c5538270faf',
        attributeName: 'Foreign Types',
        entityId: expect.any(String),
        entityName: 'MOCK_SPACE_NAME',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Project',
          type: 'entity',
        },
      },
      {
        attributeId: 'be745973-05a9-4cd0-a46d-1c5538270faf',
        attributeName: 'Foreign Types',
        entityId: expect.any(String),
        entityName: 'MOCK_SPACE_NAME',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Finance Summary',
          type: 'entity',
        },
      },
      {
        attributeId: '577bd9fb-b29e-4e2b-b5f8-f48aedbd26ac',
        attributeName: 'Row Type',
        entityId: expect.any(String),
        entityName: 'Pages',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Page',
          type: 'entity',
        },
      },
      {
        attributeId: 'b0f2d71a-79ca-4dc4-9218-e3e40dfed103',
        attributeName: 'Filter',
        entityId: expect.any(String),
        entityName: 'Pages',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value:
            '{typeIds_contains_nocase: ["1a9fc4a0-0fec-4eea-a075-eec7ebd0d043"], entityOf_: {space: "MOCK_SPACE_ADDRESS"}}',
        },
      },
      {
        attributeId: 'dd4999b9-77f0-4c2b-a02b-5a26b233854e',
        attributeName: 'Parent Entity',
        entityId: expect.any(String),
        entityName: 'Pages',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'MOCK_SPACE_NAME',
          type: 'entity',
        },
      },
      {
        attributeId: 'name',
        attributeName: 'Name',
        entityId: expect.any(String),
        entityName: 'Pages',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: 'Pages',
        },
      },
      {
        attributeId: 'type',
        attributeName: 'Types',
        entityId: expect.any(String),
        entityName: 'Pages',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Table Block',
          type: 'entity',
        },
      },
      {
        attributeId: 'beaba5cb-a677-41a8-b353-77030613fc70',
        attributeName: 'Blocks',
        entityId: expect.any(String),
        entityName: 'MOCK_SPACE_NAME',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: expect.any(String),
        },
      },
      {
        attributeId: 'name',
        attributeName: 'Name',
        entityId: expect.any(String),
        entityName: 'Posts',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: 'Posts',
        },
      },
      {
        attributeId: 'type',
        attributeName: 'Types',
        entityId: expect.any(String),
        entityName: 'Posts',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Page',
          type: 'entity',
        },
      },
      {
        attributeId: '577bd9fb-b29e-4e2b-b5f8-f48aedbd26ac',
        attributeName: 'Row Type',
        entityId: expect.any(String),
        entityName: 'Posts',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Post',
          type: 'entity',
        },
      },
      {
        attributeId: 'b0f2d71a-79ca-4dc4-9218-e3e40dfed103',
        attributeName: 'Filter',
        entityId: expect.any(String),
        entityName: 'Posts',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value:
            '{typeIds_contains_nocase: ["682fbeff-41e2-42cd-a7f9-c4909136a8c5"], entityOf_: {space: "MOCK_SPACE_ADDRESS"}}',
        },
      },
      {
        attributeId: 'dd4999b9-77f0-4c2b-a02b-5a26b233854e',
        attributeName: 'Parent Entity',
        entityId: expect.any(String),
        entityName: 'Posts',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'MOCK_SPACE_NAME',
          type: 'entity',
        },
      },
      {
        attributeId: 'name',
        attributeName: 'Name',
        entityId: expect.any(String),
        entityName: 'Posts',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: 'Posts',
        },
      },
      {
        attributeId: 'type',
        attributeName: 'Types',
        entityId: expect.any(String),
        entityName: 'Posts',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Table Block',
          type: 'entity',
        },
      },
      {
        attributeId: 'beaba5cb-a677-41a8-b353-77030613fc70',
        attributeName: 'Blocks',
        entityId: expect.any(String),
        entityName: 'MOCK_SPACE_NAME',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: expect.any(String),
        },
      },
      {
        attributeId: 'name',
        attributeName: 'Name',
        entityId: expect.any(String),
        entityName: 'Finances',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: 'Finances',
        },
      },
      {
        attributeId: 'type',
        attributeName: 'Types',
        entityId: expect.any(String),
        entityName: 'Finances',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Page',
          type: 'entity',
        },
      },
      {
        attributeId: '388ad59b-1cc7-413c-a0bb-34a4de48c758',
        attributeName: 'Shown Columns',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Other revenue sources',
          type: 'entity',
        },
      },
      {
        attributeId: '388ad59b-1cc7-413c-a0bb-34a4de48c758',
        attributeName: 'Shown Columns',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Non-financial assets',
          type: 'entity',
        },
      },
      {
        attributeId: '388ad59b-1cc7-413c-a0bb-34a4de48c758',
        attributeName: 'Shown Columns',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Construction costs',
          type: 'entity',
        },
      },
      {
        attributeId: '388ad59b-1cc7-413c-a0bb-34a4de48c758',
        attributeName: 'Shown Columns',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Other expenses',
          type: 'entity',
        },
      },
      {
        attributeId: '388ad59b-1cc7-413c-a0bb-34a4de48c758',
        attributeName: 'Shown Columns',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Grants',
          type: 'entity',
        },
      },
      {
        attributeId: '388ad59b-1cc7-413c-a0bb-34a4de48c758',
        attributeName: 'Shown Columns',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Program services fees',
          type: 'entity',
        },
      },
      {
        attributeId: '388ad59b-1cc7-413c-a0bb-34a4de48c758',
        attributeName: 'Shown Columns',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Contributions',
          type: 'entity',
        },
      },
      {
        attributeId: '388ad59b-1cc7-413c-a0bb-34a4de48c758',
        attributeName: 'Shown Columns',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Salaries + Benefits',
          type: 'entity',
        },
      },
      {
        attributeId: '388ad59b-1cc7-413c-a0bb-34a4de48c758',
        attributeName: 'Shown Columns',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Total revenue',
          type: 'entity',
        },
      },
      {
        attributeId: '577bd9fb-b29e-4e2b-b5f8-f48aedbd26ac',
        attributeName: 'Row Type',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Finance Summary',
          type: 'entity',
        },
      },
      {
        attributeId: 'b0f2d71a-79ca-4dc4-9218-e3e40dfed103',
        attributeName: 'Filter',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value:
            '{typeIds_contains_nocase: ["682fbeff-41e2-42cd-a7f9-c4909136a8c5"], entityOf_: {space: "MOCK_SPACE_ADDRESS"}}',
        },
      },
      {
        attributeId: 'dd4999b9-77f0-4c2b-a02b-5a26b233854e',
        attributeName: 'Parent Entity',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Finances',
          type: 'entity',
        },
      },
      {
        attributeId: 'name',
        attributeName: 'Name',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: 'Finance Summary',
        },
      },
      {
        attributeId: 'type',
        attributeName: 'Types',
        entityId: expect.any(String),
        entityName: 'Finance Summaries',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Table Block',
          type: 'entity',
        },
      },
      {
        attributeId: 'beaba5cb-a677-41a8-b353-77030613fc70',
        attributeName: 'Blocks',
        entityId: expect.any(String),
        entityName: 'MOCK_SPACE_NAME',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: expect.any(String),
        },
      },
      {
        attributeId: 'name',
        attributeName: 'Name',
        entityId: expect.any(String),
        entityName: 'Projects',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: 'Projects',
        },
      },
      {
        attributeId: 'type',
        attributeName: 'Types',
        entityId: expect.any(String),
        entityName: 'Projects',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Page',
          type: 'entity',
        },
      },
      {
        attributeId: '577bd9fb-b29e-4e2b-b5f8-f48aedbd26ac',
        attributeName: 'Row Type',
        entityId: expect.any(String),
        entityName: 'Projects',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Project',
          type: 'entity',
        },
      },
      {
        attributeId: 'b0f2d71a-79ca-4dc4-9218-e3e40dfed103',
        attributeName: 'Filter',
        entityId: expect.any(String),
        entityName: 'Projects',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value:
            '{typeIds_contains_nocase: ["682fbeff-41e2-42cd-a7f9-c4909136a8c5"], entityOf_: {space: "MOCK_SPACE_ADDRESS"}}',
        },
      },
      {
        attributeId: 'dd4999b9-77f0-4c2b-a02b-5a26b233854e',
        attributeName: 'Parent Entity',
        entityId: expect.any(String),
        entityName: 'Projects',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Projects',
          type: 'entity',
        },
      },
      {
        attributeId: 'name',
        attributeName: 'Name',
        entityId: expect.any(String),
        entityName: 'Projects',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: 'Projects',
        },
      },
      {
        attributeId: 'type',
        attributeName: 'Types',
        entityId: expect.any(String),
        entityName: 'Projects',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Table Block',
          type: 'entity',
        },
      },
      {
        attributeId: 'beaba5cb-a677-41a8-b353-77030613fc70',
        attributeName: 'Blocks',
        entityId: expect.any(String),
        entityName: 'MOCK_SPACE_NAME',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: expect.any(String),
        },
      },
      {
        attributeId: 'name',
        attributeName: 'Name',
        entityId: expect.any(String),
        entityName: 'About Us',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: 'About Us',
        },
      },
      {
        attributeId: 'type',
        attributeName: 'Types',
        entityId: expect.any(String),
        entityName: 'About Us',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Page',
          type: 'entity',
        },
      },
      {
        attributeId: 'name',
        attributeName: 'Name',
        entityId: expect.any(String),
        entityName: 'Get Involved',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          type: 'string',
          value: 'Get Involved',
        },
      },
      {
        attributeId: 'type',
        attributeName: 'Types',
        entityId: expect.any(String),
        entityName: 'Get Involved',
        id: expect.any(String),
        space: 'MOCK_SPACE_ADDRESS',
        type: 'createTriple',
        value: {
          id: expect.any(String),
          name: 'Page',
          type: 'entity',
        },
      },
    ]);
  });
});
