/** Read the generated registry without executing the browser bundle.
 * @param {string} source
 */
export function readRegistry(source) {
  const match = source.match(/\bvar registry\s*=\s*(\{[\s\S]*?\});/)
  if (!match)
    throw new Error(
      'Upstream registry format changed; review the vendor script'
    )
  return JSON.parse(match[1])
}

/** Keep the generated artifact and its CI drift check on the same generation path.
 * @param {string} source
 */
export function renderEventTypes(source) {
  const registry = readRegistry(source)
  const events = Object.keys(registry.events)
    .filter(
      (name) =>
        registry.events[name].apps.includes('genesis') &&
        registry.events[name].origin === 'browser'
    )
    .sort()
  if (!events.length)
    throw new Error('Upstream registry has no Genesis browser events')
  return (
    '// Generated by scripts/analytics/vendor.mjs from the upstream bundle. Do not edit.\n' +
    'export type AnalyticsEventName =\n' +
    events.map((name) => `  | '${name}'`).join('\n') +
    ';\n'
  )
}
