'use client';

import { Position, SystemIds } from '@geoprotocol/geo-sdk';
import * as Dialog from '@radix-ui/react-dialog';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useAtom, useAtomValue } from 'jotai';
import { usePathname } from 'next/navigation';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { getSchemaFromTypeIds } from '~/core/database/entities';
import { ID } from '~/core/id';
import { useCreateProperty } from '~/core/hooks/use-create-property';
import { Space } from '~/core/io/dto/spaces';
import { useMutate } from '~/core/sync/use-mutate';
import type { SwitchableRenderableType } from '~/core/types';

import { SquareButton } from '~/design-system/button';
import { ArrowLeft } from '~/design-system/icons/arrow-left';
import { PrefetchLink as Link } from '~/design-system/prefetch-link';
import { SelectEntity } from '~/design-system/select-entity';
import { Text } from '~/design-system/text';

import {
  columnMappingAtom,
  entityCountAtom,
  headersAtom,
  recordsAtom,
  selectedTypeAtom,
  valuesAtom,
} from './atoms';
import type { ColumnConfig } from './import-preview-table';
import { ImportPreviewTable } from './import-preview-table';
import { useImportGenerate } from './use-import-generate';

type ImportReviewProps = {
  spaceId: string;
  space: Space;
};

export const ImportReview = ({ spaceId }: ImportReviewProps) => {
  const pathname = usePathname();
  const spacePath = pathname?.replace(/\/import\/review$/, '') ?? `/space/${spaceId}`;

  const records = useAtomValue(recordsAtom);
  const headers = useAtomValue(headersAtom);
  const [columnMapping, setColumnMapping] = useAtom(columnMappingAtom);
  const selectedType = useAtomValue(selectedTypeAtom);
  const entityCount = useAtomValue(entityCountAtom);
  const values = useAtomValue(valuesAtom);
  const { generate, canGenerate } = useImportGenerate(spaceId);
  const hasAutoGeneratedRef = useRef(false);

  useEffect(() => {
    if (values.length === 0) hasAutoGeneratedRef.current = false;
    if (canGenerate && values.length === 0 && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      generate();
    }
  }, [canGenerate, values.length, generate]);

  const queryClient = useQueryClient();
  const { storage } = useMutate();
  const { createProperty } = useCreateProperty(spaceId);
  const [createPropertyForColumn, setCreatePropertyForColumn] = useState<number | null>(null);

  const { data: schema = [] } = useQuery({
    queryKey: ['import-schema', selectedType?.id],
    queryFn: () => getSchemaFromTypeIds([{ id: selectedType!.id }]),
    enabled: Boolean(selectedType?.id),
  });

  const handleCreatePropertyDone = useCallback(
    (result: { id: string; name: string | null } | null) => {
      if (createPropertyForColumn === null) return;
      if (result) {
        setColumnMapping(prev => ({ ...prev, [createPropertyForColumn]: result.id }));
        queryClient.invalidateQueries({ queryKey: ['import-schema', selectedType?.id] });
      }
      setCreatePropertyForColumn(null);
    },
    [createPropertyForColumn, selectedType?.id, setColumnMapping, queryClient]
  );

  const handleCreatePropertyCreate = useCallback(
    (result: {
      id: string;
      name: string | null;
      space?: string;
      verified?: boolean;
      renderableType?: SwitchableRenderableType;
    }) => {
      if (createPropertyForColumn === null || !selectedType) return undefined;
      const renderableType = result.renderableType ?? 'TEXT';
      const createdPropertyId = createProperty({
        name: result.name ?? 'New property',
        propertyType: renderableType,
        verified: result.verified ?? false,
        space: result.space,
      });
      storage.relations.set({
        id: ID.createEntityId(),
        entityId: ID.createEntityId(),
        spaceId,
        position: Position.generate(),
        renderableType: 'RELATION',
        type: { id: SystemIds.PROPERTIES, name: 'Properties' },
        fromEntity: { id: selectedType.id, name: selectedType.name },
        toEntity: {
          id: createdPropertyId,
          name: result.name ?? 'New property',
          value: createdPropertyId,
        },
        isLocal: true,
      });
      setColumnMapping(prev => ({ ...prev, [createPropertyForColumn]: createdPropertyId }));
      queryClient.invalidateQueries({ queryKey: ['import-schema', selectedType.id] });
      setCreatePropertyForColumn(null);
      return createdPropertyId;
    },
    [
      createPropertyForColumn,
      selectedType,
      createProperty,
      storage.relations,
      spaceId,
      setColumnMapping,
      queryClient,
    ]
  );

  const columns: ColumnConfig[] = useMemo(() => {
    const propIdToName = new Map(schema.map(p => [p.id, p.name ?? p.id]));
    return headers.map((headerLabel, csvColumnIndex) => {
      const propertyId = columnMapping[csvColumnIndex];
      const propertyName = propertyId ? (propIdToName.get(propertyId) ?? propertyId) : null;
      return {
        csvColumnIndex,
        headerLabel: headerLabel?.trim() || `Column ${csvColumnIndex + 1}`,
        propertyName,
      };
    });
  }, [headers, columnMapping, schema]);

  const dataRows = useMemo(
    () => records.slice(1).filter(row => Array.isArray(row) && row.some(cell => cell?.trim() !== '')),
    [records]
  );

  const hasData = dataRows.length > 0 && columns.length > 0;
  const hasRecordsButNoDataRows = records.length >= 1 && dataRows.length === 0;
  const hasNoRecords = records.length === 0;

  return (
    <div className="overflow-visible">
      <div className="mb-6">
        <Link href={`${spacePath}/import`}>
          <SquareButton icon={<ArrowLeft />} />
        </Link>
      </div>

      <h1 className="mb-2 text-mainPage font-semibold text-text">Map properties and data</h1>
      <p className="mb-6 text-metadata text-grey-04">
        Map properties to relevant properties in the space, and map any data to entities you want the data to link to.
      </p>

      <div className="mb-4 flex items-center gap-2">
        <Text variant="metadata" className="text-grey-04">
          Projects
        </Text>
        <span className="flex h-6 min-w-6 items-center justify-center rounded-full bg-grey-02 px-2 text-metadata text-text">
          {entityCount}
        </span>
      </div>

      {hasNoRecords ? (
        <div className="flex min-h-[200px] items-center justify-center rounded-lg border border-grey-02 bg-grey-01">
          <Text variant="metadata" className="text-grey-04">
            Upload a CSV file on the import page to see your data here.
          </Text>
        </div>
      ) : hasRecordsButNoDataRows ? (
        <div className="flex min-h-[200px] items-center justify-center rounded-lg border border-grey-02 bg-grey-01">
          <Text variant="metadata" className="text-grey-04">
            No data rows found. Add at least one row below the header in your CSV.
          </Text>
        </div>
      ) : !hasData ? (
        <div className="flex min-h-[200px] items-center justify-center rounded-lg border border-grey-02 bg-grey-01">
          <Text variant="metadata" className="text-grey-04">
            Select a type on the import page to see column mapping and data preview.
          </Text>
        </div>
      ) : (
        <>
          <ImportPreviewTable
            dataRows={dataRows}
            columns={columns}
            minHeight={420}
            schema={schema}
            onSelectProperty={(csvColumnIndex, propertyId) =>
              setColumnMapping(prev => ({ ...prev, [csvColumnIndex]: propertyId }))
            }
            onRequestCreateProperty={setCreatePropertyForColumn}
          />
          <Dialog.Root
            open={createPropertyForColumn !== null}
            onOpenChange={open => !open && setCreatePropertyForColumn(null)}
          >
            <Dialog.Portal>
              <Dialog.Overlay className="fixed inset-0 z-50 bg-black/20" />
              <Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-full max-w-[434px] -translate-x-1/2 -translate-y-1/2 overflow-hidden rounded-lg border border-grey-02 bg-white shadow-dropdown">
                <div className="p-2">
                  <Text variant="smallButton" className="mb-2 text-grey-04">
                    Find or create property
                  </Text>
                  <SelectEntity
                    spaceId={spaceId}
                    relationValueTypes={[{ id: SystemIds.PROPERTY, name: 'Property' }]}
                    placeholder="Search properties..."
                    onDone={handleCreatePropertyDone}
                    onCreateEntity={handleCreatePropertyCreate}
                    variant="floating"
                    advanced={false}
                    showIDs={false}
                    withSearchIcon
                  />
                </div>
              </Dialog.Content>
            </Dialog.Portal>
          </Dialog.Root>
        </>
      )}
    </div>
  );
};
