'use client';

import { useCallback, useEffect, useMemo, useRef } from 'react';

import { useAtom, useAtomValue } from 'jotai';
import { usePathname } from 'next/navigation';

import { useEditable } from '~/core/state/editable-store';
import { useSyncEngine } from '~/core/sync/use-sync-engine';
import { Property } from '~/core/types';

import { SquareButton } from '~/design-system/button';
import { ArrowLeft } from '~/design-system/icons/arrow-left';
import { Check } from '~/design-system/icons/check';
import { Warning } from '~/design-system/icons/warning';
import { PrefetchLink as Link } from '~/design-system/prefetch-link';
import { Spinner } from '~/design-system/spinner';
import { Text } from '~/design-system/text';

import {
  checkboxOverridesAtom,
  columnMappingAtom,
  entityCountAtom,
  extraPropertiesAtom,
  relationOverridesAtom,
  resolvedEntitiesSnapshotAtom,
  resolvedRowsSnapshotAtom,
  resolvedTypesSnapshotAtom,
  rowOverridesAtom,
  selectedTypeAtom,
  typeOverridesAtom,
  typesColumnIndexAtom,
  unresolvedLinksAtom,
  valuesAtom,
} from './atoms';
import type { ColumnConfig } from './import-preview-table';
import { ImportPreviewTable } from './import-preview-table';
import { useImportData } from './use-import-data';
import { useImportGenerate } from './use-import-generate';
import { useImportSchema } from './use-import-schema';
import { useImportSession } from './use-import-session';

type ImportReviewProps = {
  spaceId: string;
};

export const ImportReview = ({ spaceId }: ImportReviewProps) => {
  const pathname = usePathname();
  const spacePath = pathname?.replace(/\/import\/review$/, '') ?? `/space/${spaceId}`;
  const { setEditable } = useEditable();

  // Ensure edit mode is active on the review screen
  useEffect(() => {
    setEditable(true);
  }, [setEditable]);

  const { headers, rows: dataRows } = useImportData();
  const [columnMapping, setColumnMapping] = useAtom(columnMappingAtom);
  const [extraProperties, setExtraProperties] = useAtom(extraPropertiesAtom);
  const [checkboxOverrides, setCheckboxOverrides] = useAtom(checkboxOverridesAtom);
  const [, setRelationOverrides] = useAtom(relationOverridesAtom);
  const [, setRowOverrides] = useAtom(rowOverridesAtom);
  const [, setTypeOverrides] = useAtom(typeOverridesAtom);
  const selectedType = useAtomValue(selectedTypeAtom);
  const typesColumnIndex = useAtomValue(typesColumnIndexAtom);
  const unresolvedLinks = useAtomValue(unresolvedLinksAtom);
  const resolvedRowsSnapshot = useAtomValue(resolvedRowsSnapshotAtom);
  const resolvedTypesSnapshot = useAtomValue(resolvedTypesSnapshotAtom);
  const resolvedEntitiesSnapshot = useAtomValue(resolvedEntitiesSnapshotAtom);
  const entityCount = useAtomValue(entityCountAtom);
  const { store } = useSyncEngine();
  const values = useAtomValue(valuesAtom);
  const { generate, canGenerate, isLoading } = useImportGenerate(spaceId);
  const { clearGeneratedChanges, deleteImportColumns } = useImportSession(spaceId);
  const hasAutoGeneratedRef = useRef(false);

  // Check if all columns are mapped before triggering generation.
  // This avoids running the full relation resolution pipeline while the
  // user is still mapping columns.
  const allColumnsMapped = useMemo(() => {
    return headers.every(
      (_, i) => (typesColumnIndex !== undefined && i === typesColumnIndex) || columnMapping[i] !== undefined
    );
  }, [headers, columnMapping, typesColumnIndex]);

  useEffect(() => {
    if (!canGenerate || !allColumnsMapped) {
      hasAutoGeneratedRef.current = false;
      return;
    }
    if (canGenerate && values.length === 0 && !isLoading && !hasAutoGeneratedRef.current) {
      hasAutoGeneratedRef.current = true;
      generate()
        .then(didRun => {
          if (!didRun) hasAutoGeneratedRef.current = false;
        })
        .catch(() => {
          hasAutoGeneratedRef.current = false;
        });
    }
  }, [canGenerate, allColumnsMapped, values.length, isLoading, generate]);

  const { schema } = useImportSchema({ selectedTypeId: selectedType?.id, spaceId });

  const handleSelectProperty = useCallback(
    (csvColumnIndex: number, propertyId: string, property: Property) => {
      setColumnMapping(prev => ({ ...prev, [csvColumnIndex]: propertyId }));

      // Store in extraProperties if not already in the type's schema
      const inSchema = schema.some(p => p.id === propertyId);
      if (!inSchema) {
        setExtraProperties(prev => ({ ...prev, [propertyId]: property }));
      }

      // Clear generated values so auto-generate re-fires once all columns are mapped
      hasAutoGeneratedRef.current = false;
      clearGeneratedChanges();
    },
    [schema, setColumnMapping, setExtraProperties, clearGeneratedChanges]
  );

  const handleCreateProperty = useCallback(
    (csvColumnIndex: number, propertyId: string, property: Property) => {
      setColumnMapping(prev => ({ ...prev, [csvColumnIndex]: propertyId }));
      setExtraProperties(prev => ({ ...prev, [propertyId]: property }));

      // Clear generated values so auto-generate re-fires once all columns are mapped
      hasAutoGeneratedRef.current = false;
      clearGeneratedChanges();
    },
    [setColumnMapping, setExtraProperties, clearGeneratedChanges]
  );

  const handleResolveRelationToken = useCallback(
    (
      csvColumnIndex: number,
      token: string,
      entity: { id: string; name: string },
      isNew?: boolean,
      relationType?: { id: string; name: string | null }
    ) => {
      const propertyId = columnMapping[csvColumnIndex];
      if (!propertyId || !token.trim()) return;

      setRelationOverrides(prev => ({
        ...prev,
        [`${propertyId}::${token}`]: {
          id: entity.id,
          name: entity.name,
          status: isNew ? 'created' : 'found',
          typeId: isNew ? relationType?.id : undefined,
          typeName: isNew ? relationType?.name : undefined,
        },
      }));
    },
    [columnMapping, setRelationOverrides]
  );

  const handleResolveTypeValue = useCallback(
    (rawType: string, entity: { id: string; name: string }, isNew?: boolean) => {
      if (!rawType.trim()) return;
      setTypeOverrides(prev => ({
        ...prev,
        [rawType]: { ...entity, isNew },
      }));
    },
    [setTypeOverrides]
  );

  const handleResolveEntityRow = useCallback(
    (rowIndex: number, entity: { id: string; name: string }) => {
      setRowOverrides(prev => ({
        ...prev,
        [rowIndex]: { entityId: entity.id, name: entity.name },
      }));
    },
    [setRowOverrides]
  );

  const handleResolveCheckboxValue = useCallback(
    (rowIndex: number, csvColumnIndex: number, value: string) => {
      const cellKey = `${rowIndex}:${csvColumnIndex}`;
      setCheckboxOverrides(prev => ({ ...prev, [cellKey]: value }));
    },
    [setCheckboxOverrides]
  );

  const handleDeleteColumn = useCallback(
    (csvColumnIndex: number) => {
      deleteImportColumns([csvColumnIndex]);
      hasAutoGeneratedRef.current = false;
    },
    [deleteImportColumns]
  );

  const handleSkipAndDeleteUnmapped = useCallback(() => {
    const indices = headers
      .map((_, i) => i)
      .filter(i => {
        if (typesColumnIndex !== undefined && i === typesColumnIndex) return false;
        return columnMapping[i] === undefined;
      });
    if (indices.length === 0) return;
    deleteImportColumns(indices);
    hasAutoGeneratedRef.current = false;
  }, [headers, columnMapping, typesColumnIndex, deleteImportColumns]);

  const columns: ColumnConfig[] = useMemo(() => {
    const propIdToName = new Map(schema.map(p => [p.id, p.name ?? p.id]));
    return headers.map((headerLabel, csvColumnIndex) => {
      const isTypesSourceColumn = typesColumnIndex !== undefined && csvColumnIndex === typesColumnIndex;
      const propertyId = columnMapping[csvColumnIndex];
      const prop = propertyId
        ? (schema.find(p => p.id === propertyId) ?? extraProperties[propertyId] ?? store.getProperty(propertyId))
        : null;
      const propertyName = isTypesSourceColumn
        ? 'Types (from CSV)'
        : propertyId
          ? (propIdToName.get(propertyId) ?? extraProperties[propertyId]?.name ?? prop?.name ?? propertyId)
          : null;
      return {
        csvColumnIndex,
        headerLabel: headerLabel?.trim() || `Column ${csvColumnIndex + 1}`,
        propertyName,
        dataType: prop?.dataType,
        propertyId: propertyId ?? null,
        relationValueTypes: prop?.relationValueTypes,
        mappingLocked: isTypesSourceColumn,
        renderableTypeStrict: prop?.renderableTypeStrict,
      };
    });
  }, [headers, columnMapping, schema, extraProperties, store, typesColumnIndex]);

  const hasUnmappedColumns = columns.some(c => c.propertyName === null && !c.mappingLocked);
  const unmappedCount = columns.filter(c => c.propertyName === null && !c.mappingLocked).length;
  const unresolvedDataCount = Object.keys(unresolvedLinks).length;
  const hasData = dataRows.length > 0 && columns.length > 0;
  const hasRecordsButNoDataRows = headers.length > 0 && dataRows.length === 0;
  const hasNoRecords = headers.length === 0;

  return (
    <div className="overflow-visible">
      <div className="mb-6">
        <Link href={`${spacePath}/import`}>
          <SquareButton icon={<ArrowLeft />} />
        </Link>
      </div>

      <h1 className="mb-2 text-mainPage font-semibold text-text">Map properties and data</h1>
      <p className="mb-6 text-metadata text-grey-04">
        Map properties to relevant properties in the space, and map any data to entities you want the data to link to.
      </p>

      <div className="mb-4 flex items-center gap-2">
        <Text variant="metadata" className="text-grey-04">
          {selectedType?.name ?? 'Entities'}
        </Text>
        <span className="flex h-6 min-w-6 items-center justify-center rounded-full bg-grey-02 px-2 text-metadata text-text">
          {entityCount}
        </span>
      </div>

      {hasNoRecords ? (
        <div className="flex min-h-[200px] items-center justify-center rounded-lg border border-grey-02 bg-grey-01">
          <Text variant="metadata" className="text-grey-04">
            Upload a CSV file on the import page to see your data here.
          </Text>
        </div>
      ) : hasRecordsButNoDataRows ? (
        <div className="flex min-h-[200px] items-center justify-center rounded-lg border border-grey-02 bg-grey-01">
          <Text variant="metadata" className="text-grey-04">
            No data rows found. Add at least one row below the header in your CSV.
          </Text>
        </div>
      ) : !hasData ? (
        <div className="flex min-h-[200px] items-center justify-center rounded-lg border border-grey-02 bg-grey-01">
          <Text variant="metadata" className="text-grey-04">
            Select a type on the import page to see column mapping and data preview.
          </Text>
        </div>
      ) : isLoading ? (
        <div className="flex min-h-[420px] flex-col items-center justify-center gap-3 rounded-lg border border-grey-02 bg-grey-01">
          <Spinner />
          <Text variant="smallButton" className="text-text">
            Resolving relation data...
          </Text>
          <Text variant="metadata" className="text-grey-04">
            {entityCount} entities
          </Text>
        </div>
      ) : (
        <>
          {unmappedCount > 0 || unresolvedDataCount > 0 ? (
            <div className="mb-4 flex flex-wrap items-center gap-3 rounded-lg border border-grey-02 bg-grey-01 px-4 py-3">
              {unmappedCount > 0 && (
                <div className="flex items-center gap-1.5">
                  <span className="flex shrink-0 items-center" aria-hidden>
                    <Warning color="red-01" />
                  </span>
                  <Text variant="smallButton" className="text-text">
                    {unmappedCount} {unmappedCount === 1 ? 'property needs' : 'properties need'} linking
                  </Text>
                </div>
              )}
              {unresolvedDataCount > 0 && (
                <div className="flex items-center gap-1.5">
                  <span className="flex shrink-0 items-center" aria-hidden>
                    <Warning color="red-01" />
                  </span>
                  <Text variant="smallButton" className="text-text">
                    {unresolvedDataCount.toLocaleString('en-US')}{' '}
                    {unresolvedDataCount === 1 ? 'data point needs' : 'data points need'} linking
                  </Text>
                </div>
              )}
            </div>
          ) : values.length > 0 ? (
            <div className="mb-4 flex items-center gap-1.5 rounded-lg border border-grey-02 bg-grey-01 px-4 py-3">
              <span className="flex shrink-0 items-center" aria-hidden>
                <Check color="green" />
              </span>
              <Text variant="smallButton" className="text-text">
                All properties and data points are linked
              </Text>
            </div>
          ) : null}
          <ImportPreviewTable
            dataRows={dataRows}
            columns={columns}
            minHeight={420}
            spaceId={spaceId}
            unresolvedLinks={unresolvedLinks}
            onResolveRelationToken={handleResolveRelationToken}
            onResolveTypeValue={handleResolveTypeValue}
            onResolveEntityRow={handleResolveEntityRow}
            onResolveCheckboxValue={handleResolveCheckboxValue}
            onSelectProperty={handleSelectProperty}
            onCreateProperty={handleCreateProperty}
            hasUnmappedColumns={hasUnmappedColumns}
            resolvedRows={resolvedRowsSnapshot}
            resolvedEntities={resolvedEntitiesSnapshot}
            columnMapping={columnMapping}
            typesColumnIndex={typesColumnIndex}
            selectedType={selectedType}
            resolvedTypes={resolvedTypesSnapshot}
            checkboxOverrides={checkboxOverrides}
            onDeleteColumn={handleDeleteColumn}
            onSkipAndDeleteUnmapped={handleSkipAndDeleteUnmapped}
          />
        </>
      )}
    </div>
  );
};
