export { abi as SpaceAbi } from './space'
export { abi as MainVotingAbi } from './main-voting'
export { abi as DaoAbi } from './dao'
export { abi as MemberAccessAbi } from './member-access'
export { abi as GovernanceSetupAbi } from './governance-setup'
export { abi as PluginSetupProcessorAbi } from './plugin-setup-processor'
