/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as EpisodesRouteImport } from './routes/episodes'
import { Route as AuthenticateSuccessRouteImport } from './routes/authenticate-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsShowIdRouteImport } from './routes/shows_/$showId'
import { Route as EpisodesEpisodeIdRouteImport } from './routes/episodes_/$episodeId'
import { Route as TopicsShowsTopicIdRouteImport } from './routes/topics/shows/$topicId'
import { Route as TopicsEpisodesTopicIdRouteImport } from './routes/topics/episodes/$topicId'

const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesRoute = EpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticateSuccessRoute = AuthenticateSuccessRouteImport.update({
  id: '/authenticate-success',
  path: '/authenticate-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdRoute = ShowsShowIdRouteImport.update({
  id: '/shows_/$showId',
  path: '/shows/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesEpisodeIdRoute = EpisodesEpisodeIdRouteImport.update({
  id: '/episodes_/$episodeId',
  path: '/episodes/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsShowsTopicIdRoute = TopicsShowsTopicIdRouteImport.update({
  id: '/shows/$topicId',
  path: '/shows/$topicId',
  getParentRoute: () => TopicsRoute,
} as any)
const TopicsEpisodesTopicIdRoute = TopicsEpisodesTopicIdRouteImport.update({
  id: '/episodes/$topicId',
  path: '/episodes/$topicId',
  getParentRoute: () => TopicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticate-success': typeof AuthenticateSuccessRoute
  '/episodes': typeof EpisodesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/shows': typeof ShowsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/topics/episodes/$topicId': typeof TopicsEpisodesTopicIdRoute
  '/topics/shows/$topicId': typeof TopicsShowsTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticate-success': typeof AuthenticateSuccessRoute
  '/episodes': typeof EpisodesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/shows': typeof ShowsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/episodes/$episodeId': typeof EpisodesEpisodeIdRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/topics/episodes/$topicId': typeof TopicsEpisodesTopicIdRoute
  '/topics/shows/$topicId': typeof TopicsShowsTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authenticate-success': typeof AuthenticateSuccessRoute
  '/episodes': typeof EpisodesRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/shows': typeof ShowsRoute
  '/topics': typeof TopicsRouteWithChildren
  '/episodes_/$episodeId': typeof EpisodesEpisodeIdRoute
  '/shows_/$showId': typeof ShowsShowIdRoute
  '/topics/episodes/$topicId': typeof TopicsEpisodesTopicIdRoute
  '/topics/shows/$topicId': typeof TopicsShowsTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticate-success'
    | '/episodes'
    | '/saved'
    | '/search'
    | '/shows'
    | '/topics'
    | '/episodes/$episodeId'
    | '/shows/$showId'
    | '/topics/episodes/$topicId'
    | '/topics/shows/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticate-success'
    | '/episodes'
    | '/saved'
    | '/search'
    | '/shows'
    | '/topics'
    | '/episodes/$episodeId'
    | '/shows/$showId'
    | '/topics/episodes/$topicId'
    | '/topics/shows/$topicId'
  id:
    | '__root__'
    | '/'
    | '/authenticate-success'
    | '/episodes'
    | '/saved'
    | '/search'
    | '/shows'
    | '/topics'
    | '/episodes_/$episodeId'
    | '/shows_/$showId'
    | '/topics/episodes/$topicId'
    | '/topics/shows/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticateSuccessRoute: typeof AuthenticateSuccessRoute
  EpisodesRoute: typeof EpisodesRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  ShowsRoute: typeof ShowsRoute
  TopicsRoute: typeof TopicsRouteWithChildren
  EpisodesEpisodeIdRoute: typeof EpisodesEpisodeIdRoute
  ShowsShowIdRoute: typeof ShowsShowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes': {
      id: '/episodes'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof EpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticate-success': {
      id: '/authenticate-success'
      path: '/authenticate-success'
      fullPath: '/authenticate-success'
      preLoaderRoute: typeof AuthenticateSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows_/$showId': {
      id: '/shows_/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof ShowsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes_/$episodeId': {
      id: '/episodes_/$episodeId'
      path: '/episodes/$episodeId'
      fullPath: '/episodes/$episodeId'
      preLoaderRoute: typeof EpisodesEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/shows/$topicId': {
      id: '/topics/shows/$topicId'
      path: '/shows/$topicId'
      fullPath: '/topics/shows/$topicId'
      preLoaderRoute: typeof TopicsShowsTopicIdRouteImport
      parentRoute: typeof TopicsRoute
    }
    '/topics/episodes/$topicId': {
      id: '/topics/episodes/$topicId'
      path: '/episodes/$topicId'
      fullPath: '/topics/episodes/$topicId'
      preLoaderRoute: typeof TopicsEpisodesTopicIdRouteImport
      parentRoute: typeof TopicsRoute
    }
  }
}

interface TopicsRouteChildren {
  TopicsEpisodesTopicIdRoute: typeof TopicsEpisodesTopicIdRoute
  TopicsShowsTopicIdRoute: typeof TopicsShowsTopicIdRoute
}

const TopicsRouteChildren: TopicsRouteChildren = {
  TopicsEpisodesTopicIdRoute: TopicsEpisodesTopicIdRoute,
  TopicsShowsTopicIdRoute: TopicsShowsTopicIdRoute,
}

const TopicsRouteWithChildren =
  TopicsRoute._addFileChildren(TopicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticateSuccessRoute: AuthenticateSuccessRoute,
  EpisodesRoute: EpisodesRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  ShowsRoute: ShowsRoute,
  TopicsRoute: TopicsRouteWithChildren,
  EpisodesEpisodeIdRoute: EpisodesEpisodeIdRoute,
  ShowsShowIdRoute: ShowsShowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
