[package]
name = "geo_substream"
version = "1.0.0"
edition = "2021"

[lib]
name = "geo_substream"
crate-type = ["cdylib"]

[dependencies]
substreams = "0.5.12"
substreams-ethereum = "0.9"
prost = "0.11"
prost-types = "0.11"
base64 = "0.21.2"
ethabi = "18.0.0"
serde_json = "1.0.104"
serde = { version = "1.0.180", features = ["derive"] }
num-bigint = "0.4.4"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"