/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as conditions from './conditions/index'
import type * as governance from './governance/index'
import type * as personal from './personal/index'
import type * as space from './space/index'
import type * as test from './test/index'

export type { conditions }

export type { governance }

export type { personal }

export type { space }

export type { test }
export * as factories from './factories/index'
export type { PersonalSpaceAdminPlugin } from './personal/PersonalSpaceAdminPlugin'
export { PersonalSpaceAdminPlugin__factory } from './factories/personal/PersonalSpaceAdminPlugin__factory'
export type { PersonalSpaceAdminPluginSetup } from './personal/PersonalSpaceAdminPluginSetup'
export { PersonalSpaceAdminPluginSetup__factory } from './factories/personal/PersonalSpaceAdminPluginSetup__factory'
export type { PersonalSpaceAdminCloneFactory } from './test/PersonalSpaceAdminCloneFactory'
export { PersonalSpaceAdminCloneFactory__factory } from './factories/test/PersonalSpaceAdminCloneFactory__factory'
export type { TestGovernancePluginsSetup } from './test/TestGovernancePluginsSetup'
export { TestGovernancePluginsSetup__factory } from './factories/test/TestGovernancePluginsSetup__factory'
export type { TestOnlyPluginUpgraderCondition } from './test/TestOnlyPluginUpgraderCondition'
export { TestOnlyPluginUpgraderCondition__factory } from './factories/test/TestOnlyPluginUpgraderCondition__factory'
export type { TestMemberAccessPlugin } from './test/TestMemberAccessPlugin'
export { TestMemberAccessPlugin__factory } from './factories/test/TestMemberAccessPlugin__factory'
export type { TestMemberAccessExecuteCondition } from './test/TestMemberAccessExecuteCondition'
export { TestMemberAccessExecuteCondition__factory } from './factories/test/TestMemberAccessExecuteCondition__factory'
export type { MemberAccessExecuteCondition } from './conditions/MemberAccessExecuteCondition'
export { MemberAccessExecuteCondition__factory } from './factories/conditions/MemberAccessExecuteCondition__factory'
export type { OnlyPluginUpgraderCondition } from './conditions/OnlyPluginUpgraderCondition'
export { OnlyPluginUpgraderCondition__factory } from './factories/conditions/OnlyPluginUpgraderCondition__factory'
export type { MainVotingPlugin } from './governance/MainVotingPlugin'
export { MainVotingPlugin__factory } from './factories/governance/MainVotingPlugin__factory'
export type { IMembers } from './governance/base/IMembers'
export { IMembers__factory } from './factories/governance/base/IMembers__factory'
export type { MajorityVotingBase } from './governance/base/MajorityVotingBase'
export { MajorityVotingBase__factory } from './factories/governance/base/MajorityVotingBase__factory'
export type { IMultisig } from './governance/base/IMultisig'
export { IMultisig__factory } from './factories/governance/base/IMultisig__factory'
export type { Addresslist } from './governance/base/Addresslist'
export { Addresslist__factory } from './factories/governance/base/Addresslist__factory'
export type { IEditors } from './governance/base/IEditors'
export { IEditors__factory } from './factories/governance/base/IEditors__factory'
export type { GovernancePluginsSetup } from './governance/GovernancePluginsSetup'
export { GovernancePluginsSetup__factory } from './factories/governance/GovernancePluginsSetup__factory'
export type { MemberAccessPlugin } from './governance/MemberAccessPlugin'
export { MemberAccessPlugin__factory } from './factories/governance/MemberAccessPlugin__factory'
export type { SpacePluginSetup } from './space/SpacePluginSetup'
export { SpacePluginSetup__factory } from './factories/space/SpacePluginSetup__factory'
export type { SpacePlugin } from './space/SpacePlugin'
export { SpacePlugin__factory } from './factories/space/SpacePlugin__factory'
